# Generated by Django 5.2 on 2025-05-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltestsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_submissions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='analyte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='data.analyte', verbose_name='Analyte'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='data.medicaltestsubmission', verbose_name='Submission'),
        ),
        migrations.AddField(
            model_name='medicaltestsubmission',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='data.testtype', verbose_name='Test Type'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('submission', 'analyte')},
        ),
    ]
