# Generated by Django X.Y on YYYY-MM-DD HH:MM
# -*- coding: utf-8 -*-
# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations

# Список данных для аналитов
# ВАЖНО: Проверьте и уточните русские и казахские названия/аббревиатуры!
ANALYTES_DATA = [
    # 1. Hematology / Гематология / Гематология
    # CBC / ОАК / ЖҚА
    {'name': 'Гемоглобин', 'unit': 'г/л', 'name_en': 'Hemoglobin', 'name_ru': 'Гемоглобин', 'name_kk': 'Гемоглобин', 'abbr': 'Hb,Hgb,Гб'},
    {'name': 'Гематокрит', 'unit': '%', 'name_en': 'Hematocrit', 'name_ru': 'Гематокрит', 'name_kk': 'Гематокрит', 'abbr': 'Hct,PCV,Ht'},
    {'name': 'Лейкоциты', 'unit': 'x10^9/л', 'name_en': 'White Blood Cells', 'name_ru': 'Лейкоциты', 'name_kk': 'Лейкоциттер', 'abbr': 'WBC,Leu,Leuko'},
    {'name': 'Эритроциты', 'unit': 'x10^12/л', 'name_en': 'Red Blood Cells', 'name_ru': 'Эритроциты', 'name_kk': 'Эритроциттер', 'abbr': 'RBC,Ery'},
    {'name': 'Тромбоциты', 'unit': 'x10^9/л', 'name_en': 'Platelet count', 'name_ru': 'Тромбоциты', 'name_kk': 'Тромбоциттер', 'abbr': 'Plt,Thromb,PLT'},
    {'name': 'Средний объем эритроцита', 'unit': 'fL', 'name_en': 'Mean Corpuscular Volume', 'name_ru': 'Средний объем эритроцита', 'name_kk': 'Эритроциттердің орташа көлемі', 'abbr': 'MCV,СОЭ,ЭОК'},
    {'name': 'Среднее содержание гемоглобина в эритроците', 'unit': 'pg', 'name_en': 'Mean Corpuscular Hemoglobin', 'name_ru': 'Среднее содержание гемоглобина в эритроците', 'name_kk': 'Эритроциттегі гемоглобиннің орташа мөлшері', 'abbr': 'MCH'},
    {'name': 'Средняя концентрация гемоглобина в эритроците', 'unit': 'г/дл', 'name_en': 'Mean Corpuscular Hemoglobin Concentration', 'name_ru': 'Средняя концентрация гемоглобина в эритроците', 'name_kk': 'Эритроциттегі гемоглобиннің орташа концентрациясы', 'abbr': 'MCHC'},
    {'name': 'Ширина распределения эритроцитов', 'unit': '%', 'name_en': 'Red Cell Distribution Width', 'name_ru': 'Ширина распределения эритроцитов', 'name_kk': 'Эритроциттердің таралу ені', 'abbr': 'RDW,RDW-CV,RDW-SD'},
    {'name': 'Нейтрофилы', 'unit': '%', 'name_en': 'Neutrophils', 'name_ru': 'Нейтрофилы', 'name_kk': 'Нейтрофилдер', 'abbr': 'NEUT,NEU'},
    {'name': 'Лимфоциты', 'unit': '%', 'name_en': 'Lymphocytes', 'name_ru': 'Лимфоциты', 'name_kk': 'Лимфоциттер', 'abbr': 'LYMPH,LYM'},
    {'name': 'Моноциты', 'unit': '%', 'name_en': 'Monocytes', 'name_ru': 'Моноциты', 'name_kk': 'Моноциттер', 'abbr': 'MONO,MON'},
    {'name': 'Эозинофилы', 'unit': '%', 'name_en': 'Eosinophils', 'name_ru': 'Эозинофилы', 'name_kk': 'Эозинофилдер', 'abbr': 'EOS'},
    {'name': 'Базофилы', 'unit': '%', 'name_en': 'Basophils', 'name_ru': 'Базофилы', 'name_kk': 'Базофилдер', 'abbr': 'BASO'},
    # Coagulation / Коагулограмма / Коагулограмма
    {'name': 'Протромбиновое время', 'unit': 'сек', 'name_en': 'Prothrombin Time', 'name_ru': 'Протромбиновое время', 'name_kk': 'Протромбиндік уақыт', 'abbr': 'PT,ПТВ,ПВ'},
    {'name': 'Международное нормализованное отношение', 'unit': '', 'name_en': 'International Normalized Ratio', 'name_ru': 'Международное нормализованное отношение', 'name_kk': 'Халықаралық қалыптасқан қатынас', 'abbr': 'INR,МНО'},
    {'name': 'Активированное частичное тромбопластиновое время', 'unit': 'сек', 'name_en': 'Activated Partial Thromboplastin Time', 'name_ru': 'Активированное частичное тромбопластиновое время', 'name_kk': 'Белсендірілген ішінара тромбопластиндік уақыт', 'abbr': 'aPTT,АЧТВ,АПТВ'},
    {'name': 'D-димер', 'unit': 'нг/мл', 'name_en': 'D-dimer', 'name_ru': 'D-димер', 'name_kk': 'D-димер', 'abbr': 'D-dimer'},
    {'name': 'Фибриноген', 'unit': 'г/л', 'name_en': 'Fibrinogen', 'name_ru': 'Фибриноген', 'name_kk': 'Фибриноген', 'abbr': 'Fib'},

    # 2. Clinical Biochemistry / Клиническая биохимия / Клиникалық биохимия
    # Renal / Почечные / Бүйрек
    {'name': 'Креатинин', 'unit': 'мкмоль/л', 'name_en': 'Creatinine', 'name_ru': 'Креатинин', 'name_kk': 'Креатинин', 'abbr': 'Crea,Cr'},
    {'name': 'Мочевина', 'unit': 'ммоль/л', 'name_en': 'Urea', 'name_ru': 'Мочевина', 'name_kk': 'Несепнәр', 'abbr': 'Urea'},
    {'name': 'Азот мочевины крови', 'unit': 'мг/дл', 'name_en': 'Blood Urea Nitrogen', 'name_ru': 'Азот мочевины крови', 'name_kk': 'Қандағы несепнәр азоты', 'abbr': 'BUN'},
    {'name': 'Расчетная скорость клубочковой фильтрации', 'unit': 'мл/мин/1.73м²', 'name_en': 'Estimated Glomerular Filtration Rate', 'name_ru': 'Расчетная скорость клубочковой фильтрации', 'name_kk': 'Болжамды шумақтық фильтрация жылдамдығы', 'abbr': 'eGFR,СКФ'},
    {'name': 'Мочевая кислота', 'unit': 'мкмоль/л', 'name_en': 'Uric acid', 'name_ru': 'Мочевая кислота', 'name_kk': 'Несеп қышқылы', 'abbr': 'UA'},
    # LFTs / Печеночные / Бауыр
    {'name': 'Аланинаминотрансфераза', 'unit': 'Ед/л', 'name_en': 'Alanine Aminotransferase', 'name_ru': 'Аланинаминотрансфераза', 'name_kk': 'Аланинаминотрансфераза', 'abbr': 'ALT,АЛТ,АЛаТ,SGPT'},
    {'name': 'Аспартатаминотрансфераза', 'unit': 'Ед/л', 'name_en': 'Aspartate Aminotransferase', 'name_ru': 'Аспартатаминотрансфераза', 'name_kk': 'Аспартатаминотрансфераза', 'abbr': 'AST,АСТ,АСаТ,SGOT'},
    {'name': 'Щелочная фосфатаза', 'unit': 'Ед/л', 'name_en': 'Alkaline Phosphatase', 'name_ru': 'Щелочная фосфатаза', 'name_kk': 'Сілтілік фосфатаза', 'abbr': 'ALP,ЩФ,ЩФ'},
    {'name': 'Гамма-глутамилтрансфераза', 'unit': 'Ед/л', 'name_en': 'Gamma-glutamyl Transferase', 'name_ru': 'Гамма-глутамилтрансфераза', 'name_kk': 'Гамма-глутамилтрансфераза', 'abbr': 'GGT,ГГТ,ГГТП'},
    {'name': 'Билирубин общий', 'unit': 'мкмоль/л', 'name_en': 'Bilirubin, Total', 'name_ru': 'Билирубин общий', 'name_kk': 'Жалпы билирубин', 'abbr': 'T Bili,Общий билирубин'},
    {'name': 'Билирубин прямой', 'unit': 'мкмоль/л', 'name_en': 'Bilirubin, Direct', 'name_ru': 'Билирубин прямой', 'name_kk': 'Тікелей билирубин', 'abbr': 'D Bili,Прямой билирубин,Связанный билирубин'},
    {'name': 'Альбумин', 'unit': 'г/л', 'name_en': 'Albumin', 'name_ru': 'Альбумин', 'name_kk': 'Альбумин', 'abbr': 'Alb'},
    {'name': 'Общий белок', 'unit': 'г/л', 'name_en': 'Total Protein', 'name_ru': 'Общий белок', 'name_kk': 'Жалпы белок', 'abbr': 'TP'},
    # Electrolytes / Электролиты / Электролиттер
    {'name': 'Натрий', 'unit': 'ммоль/л', 'name_en': 'Sodium', 'name_ru': 'Натрий', 'name_kk': 'Натрий', 'abbr': 'Na'},
    {'name': 'Калий', 'unit': 'ммоль/л', 'name_en': 'Potassium', 'name_ru': 'Калий', 'name_kk': 'Калий', 'abbr': 'K'},
    {'name': 'Хлор', 'unit': 'ммоль/л', 'name_en': 'Chloride', 'name_ru': 'Хлор', 'name_kk': 'Хлор', 'abbr': 'Cl'},
    {'name': 'Бикарбонат', 'unit': 'ммоль/л', 'name_en': 'Bicarbonate', 'name_ru': 'Бикарбонат', 'name_kk': 'Бикарбонат', 'abbr': 'HCO3'},
    {'name': 'Общий CO2', 'unit': 'ммоль/л', 'name_en': 'Total CO2', 'name_ru': 'Общий CO2', 'name_kk': 'Жалпы CO2', 'abbr': 'TCO2'},
    {'name': 'Кальций общий', 'unit': 'ммоль/л', 'name_en': 'Calcium, Total', 'name_ru': 'Кальций общий', 'name_kk': 'Жалпы кальций', 'abbr': 'Ca,Общий кальций'},
    {'name': 'Кальций ионизированный', 'unit': 'ммоль/л', 'name_en': 'Calcium, Ionized', 'name_ru': 'Кальций ионизированный', 'name_kk': 'Иондалған кальций', 'abbr': 'iCa'},
    {'name': 'Магний', 'unit': 'ммоль/л', 'name_en': 'Magnesium', 'name_ru': 'Магний', 'name_kk': 'Магний', 'abbr': 'Mg'},
    {'name': 'Фосфор неорганический', 'unit': 'ммоль/л', 'name_en': 'Phosphate', 'name_ru': 'Фосфор неорганический', 'name_kk': 'Бейорганикалық фосфор', 'abbr': 'PO4,Phos,P'},
    # Glucose & Metabolic / Глюкоза и метаболиты / Глюкоза және метаболиттер
    {'name': 'Глюкоза', 'unit': 'ммоль/л', 'name_en': 'Glucose', 'name_ru': 'Глюкоза', 'name_kk': 'Глюкоза', 'abbr': 'Glu,GLU'},
    {'name': 'Гликированный гемоглобин', 'unit': '%', 'name_en': 'Hemoglobin A1c', 'name_ru': 'Гликированный гемоглобин', 'name_kk': 'Гликирленген гемоглобин', 'abbr': 'HbA1c,A1c'},
    {'name': 'Пероральный глюкозотолерантный тест', 'unit': 'ммоль/л', 'name_en': 'Oral Glucose Tolerance Test', 'name_ru': 'Пероральный глюкозотолерантный тест', 'name_kk': 'Пероралды глюкозаға төзімділік тесті', 'abbr': 'OGTT,ГТТ'},
    {'name': 'Лактат', 'unit': 'ммоль/л', 'name_en': 'Lactate', 'name_ru': 'Лактат', 'name_kk': 'Лактат', 'abbr': 'Lactate,Молочная кислота'},
    # Lipid Profile / Липидный профиль / Липидтік профиль
    {'name': 'Холестерин общий', 'unit': 'ммоль/л', 'name_en': 'Total Cholesterol', 'name_ru': 'Холестерин общий', 'name_kk': 'Жалпы холестерин', 'abbr': 'TC,Chol,Общий холестерин'},
    {'name': 'Холестерин ЛПНП', 'unit': 'ммоль/л', 'name_en': 'LDL Cholesterol', 'name_ru': 'Холестерин ЛПНП', 'name_kk': 'ТТЛП холестерині', 'abbr': 'LDL,ЛПНП,ЛНП'},
    {'name': 'Холестерин ЛПВП', 'unit': 'ммоль/л', 'name_en': 'HDL Cholesterol', 'name_ru': 'Холестерин ЛПВП', 'name_kk': 'ЖТЛП холестерині', 'abbr': 'HDL,ЛПВП,ЛВП'},
    {'name': 'Триглицериды', 'unit': 'ммоль/л', 'name_en': 'Triglycerides', 'name_ru': 'Триглицериды', 'name_kk': 'Триглицеридтер', 'abbr': 'TG,Trig'},
    # Cardiac Enzymes / Сердечные маркеры / Жүрек маркерлері
    {'name': 'Тропонин I', 'unit': 'нг/мл', 'name_en': 'Troponin I', 'name_ru': 'Тропонин I', 'name_kk': 'Тропонин I', 'abbr': 'TnI,cTnI'},
    {'name': 'Тропонин T', 'unit': 'нг/мл', 'name_en': 'Troponin T', 'name_ru': 'Тропонин T', 'name_kk': 'Тропонин T', 'abbr': 'TnT,cTnT'},
    {'name': 'Креатинкиназа-МВ', 'unit': 'Ед/л', 'name_en': 'Creatine Kinase-MB', 'name_ru': 'Креатинкиназа-МВ', 'name_kk': 'Креатинкиназа-МВ', 'abbr': 'CK-MB,КФК-МВ'},
    {'name': 'Миоглобин', 'unit': 'нг/мл', 'name_en': 'Myoglobin', 'name_ru': 'Миоглобин', 'name_kk': 'Миоглобин', 'abbr': 'Myo'},
    {'name': 'Натрийуретический пептид B-типа', 'unit': 'пг/мл', 'name_en': 'BNP', 'name_ru': 'Натрийуретический пептид B-типа', 'name_kk': 'B-типті натрийуретикалық пептид', 'abbr': 'BNP'},
    {'name': 'N-концевой пропептид натрийуретического гормона B-типа', 'unit': 'пг/мл', 'name_en': 'NT-proBNP', 'name_ru': 'N-концевой пропептид натрийуретического гормона B-типа', 'name_kk': 'B-типті натрийуретикалық гормонның N-терминалды пропептиді', 'abbr': 'NT-proBNP'},

    # 3. Endocrinology / Hormonal Panel / Эндокринология / Гормоны / Эндокринология / Гормондар
    {'name': 'Тиреотропный гормон', 'unit': 'мМЕ/л', 'name_en': 'Thyroid-Stimulating Hormone', 'name_ru': 'Тиреотропный гормон', 'name_kk': 'Тиреотропты гормон', 'abbr': 'TSH,ТТГ'},
    {'name': 'Тироксин свободный', 'unit': 'пмоль/л', 'name_en': 'Free T4', 'name_ru': 'Тироксин свободный', 'name_kk': 'Бос тироксин', 'abbr': 'FT4,св.Т4,Т4 св'},
    {'name': 'Трийодтиронин свободный', 'unit': 'пмоль/л', 'name_en': 'Free T3', 'name_ru': 'Трийодтиронин свободный', 'name_kk': 'Бос трийодтиронин', 'abbr': 'FT3,св.Т3,Т3 св'},
    {'name': 'Кортизол', 'unit': 'нмоль/л', 'name_en': 'Cortisol', 'name_ru': 'Кортизол', 'name_kk': 'Кортизол', 'abbr': 'Cortisol'},
    {'name': 'Адренокортикотропный гормон', 'unit': 'пг/мл', 'name_en': 'Adrenocorticotropic Hormone', 'name_ru': 'Адренокортикотропный гормон', 'name_kk': 'Адренокортикотропты гормон', 'abbr': 'ACTH,АКТГ'},
    {'name': 'Паратгормон', 'unit': 'пг/мл', 'name_en': 'Parathyroid Hormone', 'name_ru': 'Паратгормон', 'name_kk': 'Паратгормон', 'abbr': 'PTH,ПТГ'},
    {'name': 'Тестостерон общий', 'unit': 'нмоль/л', 'name_en': 'Testosterone, Total', 'name_ru': 'Тестостерон общий', 'name_kk': 'Жалпы тестостерон', 'abbr': 'Testo,Общий тестостерон'},
    {'name': 'Тестостерон свободный', 'unit': 'пг/мл', 'name_en': 'Testosterone, Free', 'name_ru': 'Тестостерон свободный', 'name_kk': 'Бос тестостерон', 'abbr': 'Free Testo,Св. тестостерон'},
    {'name': 'Эстрадиол', 'unit': 'пмоль/л', 'name_en': 'Estradiol', 'name_ru': 'Эстрадиол', 'name_kk': 'Эстрадиол', 'abbr': 'E2'},
    {'name': 'Лютеинизирующий гормон', 'unit': 'МЕ/л', 'name_en': 'Luteinizing Hormone', 'name_ru': 'Лютеинизирующий гормон', 'name_kk': 'Лютеиндеуші гормон', 'abbr': 'LH,ЛГ'},
    {'name': 'Фолликулостимулирующий гормон', 'unit': 'МЕ/л', 'name_en': 'Follicle-Stimulating Hormone', 'name_ru': 'Фолликулостимулирующий гормон', 'name_kk': 'Фолликул стимулдаушы гормон', 'abbr': 'FSH,ФСГ'},
    {'name': 'Пролактин', 'unit': 'мМЕ/л', 'name_en': 'Prolactin', 'name_ru': 'Пролактин', 'name_kk': 'Пролактин', 'abbr': 'PRL,ПРЛ'},
    {'name': 'Инсулин', 'unit': 'мкМЕ/мл', 'name_en': 'Insulin', 'name_ru': 'Инсулин', 'name_kk': 'Инсулин', 'abbr': 'Insulin'},
    {'name': 'ДГЭА-Сульфат', 'unit': 'мкмоль/л', 'name_en': 'DHEA-Sulfate', 'name_ru': 'ДГЭА-Сульфат', 'name_kk': 'ДГЭА-Сульфат', 'abbr': 'DHEA-S,ДГЭА-С'},

    # 4. Infectious Disease Testing / Инфекционные заболевания / Инфекциялық аурулар
    {'name': 'HBsAg', 'unit': '', 'name_en': 'Hepatitis B Surface Antigen', 'name_ru': 'HBs-антиген', 'name_kk': 'HBs-антиген', 'abbr': 'HBsAg'},
    {'name': 'Anti-HBc Total', 'unit': '', 'name_en': 'Hepatitis B Core Antibody (Total)', 'name_ru': 'Anti-HBc общие', 'name_kk': 'Anti-HBc жалпы', 'abbr': 'Anti-HBc,HBcAb'},
    {'name': 'Anti-HBs', 'unit': 'МЕ/л', 'name_en': 'Hepatitis B Surface Antibody', 'name_ru': 'Anti-HBs', 'name_kk': 'Anti-HBs', 'abbr': 'Anti-HBs,HBsAb'},
    {'name': 'Anti-HCV Total', 'unit': '', 'name_en': 'Hepatitis C Antibody', 'name_ru': 'Anti-HCV общие', 'name_kk': 'Anti-HCV жалпы', 'abbr': 'Anti-HCV,HCVAb'},
    {'name': 'ВИЧ (антитела и антиген)', 'unit': '', 'name_en': 'HIV 1/2 Antibody/Antigen', 'name_ru': 'ВИЧ (антитела и антиген)', 'name_kk': 'АИТВ (антиденелер және антиген)', 'abbr': 'HIV Ag/Ab,ВИЧ 1/2'},
    {'name': 'Сифилис RPR', 'unit': '', 'name_en': 'Syphilis Test (RPR)', 'name_ru': 'Сифилис RPR', 'name_kk': 'Мерез RPR', 'abbr': 'RPR,RW,Реакция Вассермана'},
    {'name': 'Сифилис TPHA', 'unit': '', 'name_en': 'Syphilis Confirmatory (TPHA)', 'name_ru': 'Сифилис TPHA', 'name_kk': 'Мерез TPHA', 'abbr': 'TPHA,РПГА'},
    {'name': 'COVID-19 (ПЦР)', 'unit': '', 'name_en': 'COVID-19 PCR', 'name_ru': 'COVID-19 (ПЦР)', 'name_kk': 'COVID-19 (ПТР)', 'abbr': 'COVID PCR,SARS-CoV-2 РНК'},
    {'name': 'COVID-19 (Антиген)', 'unit': '', 'name_en': 'COVID-19 Antigen', 'name_ru': 'COVID-19 (Антиген)', 'name_kk': 'COVID-19 (Антиген)', 'abbr': 'COVID Ag'},
    {'name': 'COVID-19 Антитела IgG', 'unit': '', 'name_en': 'COVID-19 Antibody IgG', 'name_ru': 'COVID-19 Антитела IgG', 'name_kk': 'COVID-19 Антиденелер IgG', 'abbr': 'COVID IgG,Anti-SARS-CoV-2 IgG'},
    {'name': 'COVID-19 Антитела IgM', 'unit': '', 'name_en': 'COVID-19 Antibody IgM', 'name_ru': 'COVID-19 Антитела IgM', 'name_kk': 'COVID-19 Антиденелер IgM', 'abbr': 'COVID IgM,Anti-SARS-CoV-2 IgM'},
    {'name': 'Грипп A/B', 'unit': '', 'name_en': 'Influenza A/B', 'name_ru': 'Грипп A/B', 'name_kk': 'Тұмау A/B', 'abbr': 'Flu A/B'},
    {'name': 'Вирус Эпштейна-Барр VCA IgG', 'unit': '', 'name_en': 'Epstein-Barr Virus VCA IgG', 'name_ru': 'Вирус Эпштейна-Барр VCA IgG', 'name_kk': 'Эпштейн-Барр вирусы VCA IgG', 'abbr': 'EBV VCA IgG,ВЭБ VCA IgG'},
    {'name': 'Вирус Эпштейна-Барр VCA IgM', 'unit': '', 'name_en': 'Epstein-Barr Virus VCA IgM', 'name_ru': 'Вирус Эпштейна-Барр VCA IgM', 'name_kk': 'Эпштейн-Барр вирусы VCA IgM', 'abbr': 'EBV VCA IgM,ВЭБ VCA IgM'},
    {'name': 'Вирус Эпштейна-Барр EBNA IgG', 'unit': '', 'name_en': 'Epstein-Barr Virus EBNA IgG', 'name_ru': 'Вирус Эпштейна-Барр EBNA IgG', 'name_kk': 'Эпштейн-Барр вирусы EBNA IgG', 'abbr': 'EBV EBNA IgG,ВЭБ EBNA IgG'},
    {'name': 'Цитомегаловирус IgG', 'unit': '', 'name_en': 'Cytomegalovirus IgG', 'name_ru': 'Цитомегаловирус IgG', 'name_kk': 'Цитомегаловирус IgG', 'abbr': 'CMV IgG,ЦМВ IgG'},
    {'name': 'Цитомегаловирус IgM', 'unit': '', 'name_en': 'Cytomegalovirus IgM', 'name_ru': 'Цитомегаловирус IgM', 'name_kk': 'Цитомегаловирус IgM', 'abbr': 'CMV IgM,ЦМВ IgM'},
    {'name': 'Квантифероновый тест', 'unit': 'МЕ/мл', 'name_en': 'Tuberculosis Test (Quantiferon)', 'name_ru': 'Квантифероновый тест', 'name_kk': 'Квантиферондық тест', 'abbr': 'QFT,IGRA'},
    {'name': 'Проба Манту', 'unit': 'мм', 'name_en': 'Tuberculosis Test (Mantoux)', 'name_ru': 'Проба Манту', 'name_kk': 'Манту сынамасы', 'abbr': 'PPD,Манту'},

    # 5. Urinalysis / Общий анализ мочи / Жалпы несеп анализі
    {'name': 'Цвет мочи', 'unit': '', 'name_en': 'Urine Color', 'name_ru': 'Цвет мочи', 'name_kk': 'Несеп түсі', 'abbr': 'Color,Цвет'},
    {'name': 'Прозрачность мочи', 'unit': '', 'name_en': 'Urine Clarity', 'name_ru': 'Прозрачность мочи', 'name_kk': 'Несеп мөлдірлігі', 'abbr': 'Clarity,Прозрачность'},
    {'name': 'pH мочи', 'unit': '', 'name_en': 'Urine pH', 'name_ru': 'pH мочи', 'name_kk': 'Несеп рН', 'abbr': 'pH'},
    {'name': 'Удельный вес мочи', 'unit': '', 'name_en': 'Urine Specific Gravity', 'name_ru': 'Удельный вес мочи', 'name_kk': 'Несептің меншікті салмағы', 'abbr': 'SG,Уд.вес'},
    {'name': 'Белок в моче', 'unit': 'г/л', 'name_en': 'Urine Protein', 'name_ru': 'Белок в моче', 'name_kk': 'Несептегі белок', 'abbr': 'Protein,PRO,Белок'},
    {'name': 'Глюкоза в моче', 'unit': '', 'name_en': 'Urine Glucose', 'name_ru': 'Глюкоза в моче', 'name_kk': 'Несептегі глюкоза', 'abbr': 'Glucose,GLU,Сахар'},
    {'name': 'Кетоны в моче', 'unit': '', 'name_en': 'Urine Ketones', 'name_ru': 'Кетоны в моче', 'name_kk': 'Несептегі кетондар', 'abbr': 'Ketones,KET,Кетоновые тела'},
    {'name': 'Кровь в моче', 'unit': '', 'name_en': 'Urine Blood', 'name_ru': 'Кровь в моче', 'name_kk': 'Несептегі қан', 'abbr': 'Blood,BLD,Эритроциты (хим)'},
    {'name': 'Билирубин в моче', 'unit': '', 'name_en': 'Urine Bilirubin', 'name_ru': 'Билирубин в моче', 'name_kk': 'Несептегі билирубин', 'abbr': 'Bilirubin,BIL'},
    {'name': 'Уробилиноген в моче', 'unit': '', 'name_en': 'Urine Urobilinogen', 'name_ru': 'Уробилиноген в моче', 'name_kk': 'Несептегі уробилиноген', 'abbr': 'Urobilinogen,URO'},
    {'name': 'Нитриты в моче', 'unit': '', 'name_en': 'Urine Nitrite', 'name_ru': 'Нитриты в моче', 'name_kk': 'Несептегі нитриттер', 'abbr': 'Nitrite,NIT'},
    {'name': 'Лейкоциты в моче (эстераза)', 'unit': '', 'name_en': 'Urine Leukocyte Esterase', 'name_ru': 'Лейкоцитарная эстераза', 'name_kk': 'Лейкоцитарлық эстераза', 'abbr': 'LEU,Лейкоциты (хим)'},
    {'name': 'Эритроциты в моче (микроскопия)', 'unit': 'в п/з', 'name_en': 'Urine Red Blood Cells (micro)', 'name_ru': 'Эритроциты (микроскопия)', 'name_kk': 'Эритроциттер (микроскопия)', 'abbr': 'RBC mic'},
    {'name': 'Лейкоциты в моче (микроскопия)', 'unit': 'в п/з', 'name_en': 'Urine White Blood Cells (micro)', 'name_ru': 'Лейкоциты (микроскопия)', 'name_kk': 'Лейкоциттер (микроскопия)', 'abbr': 'WBC mic'},
    {'name': 'Эпителий плоский', 'unit': 'в п/з', 'name_en': 'Squamous Epithelial Cells', 'name_ru': 'Эпителий плоский', 'name_kk': 'Жалпақ эпителий', 'abbr': 'Epith,Эпит. пл.'},
    {'name': 'Цилиндры гиалиновые', 'unit': 'в п/з', 'name_en': 'Hyaline Casts', 'name_ru': 'Цилиндры гиалиновые', 'name_kk': 'Гиалинді цилиндрлер', 'abbr': 'Casts hyal'},
    {'name': 'Кристаллы в моче', 'unit': '', 'name_en': 'Urine Crystals', 'name_ru': 'Кристаллы в моче', 'name_kk': 'Несептегі кристалдар', 'abbr': 'Crystals,Кристаллы'},
    {'name': 'Бактерии в моче', 'unit': '', 'name_en': 'Urine Bacteria', 'name_ru': 'Бактерии в моче', 'name_kk': 'Несептегі бактериялар', 'abbr': 'Bacteria,Бактерии'},
    {'name': 'Соотношение Белок/Креатинин в моче', 'unit': 'мг/г', 'name_en': 'Urine Protein-to-Creatinine Ratio', 'name_ru': 'Соотношение Белок/Креатинин в моче', 'name_kk': 'Несептегі Белок/Креатинин қатынасы', 'abbr': 'UPCR'},
    {'name': 'Суточный белок в моче', 'unit': 'г/сут', 'name_en': '24-hour Urine Protein', 'name_ru': 'Суточный белок в моче', 'name_kk': 'Тәуліктік несептегі белок', 'abbr': '24h Protein'},

    # 6. Immunology / Autoimmune Panels / Иммунология / Аутоиммунные панели / Иммунология / Аутоиммунды панельдер
    {'name': 'С-реактивный белок', 'unit': 'мг/л', 'name_en': 'C-Reactive Protein', 'name_ru': 'С-реактивный белок', 'name_kk': 'С-реактивті белок', 'abbr': 'CRP,СРБ'},
    {'name': 'Скорость оседания эритроцитов', 'unit': 'мм/час', 'name_en': 'Erythrocyte Sedimentation Rate', 'name_ru': 'Скорость оседания эритроцитов', 'name_kk': 'Эритроциттердің тұну жылдамдығы', 'abbr': 'ESR,СОЭ,ЭТЖ'},
    {'name': 'Ревматоидный фактор', 'unit': 'МЕ/мл', 'name_en': 'Rheumatoid Factor', 'name_ru': 'Ревматоидный фактор', 'name_kk': 'Ревматоидты фактор', 'abbr': 'RF,РФ'},
    {'name': 'Антинуклеарный фактор', 'unit': '', 'name_en': 'Anti-Nuclear Antibody', 'name_ru': 'Антинуклеарный фактор', 'name_kk': 'Антинуклеарлы фактор', 'abbr': 'ANA,АНФ,АНА'}, # ANA часто имеет титр и паттерн
    {'name': 'Антитела к дсДНК', 'unit': 'МЕ/мл', 'name_en': 'Anti-dsDNA Antibody', 'name_ru': 'Антитела к двуспиральной ДНК', 'name_kk': 'Қос спиральды ДНҚ-ға антиденелер', 'abbr': 'Anti-dsDNA,АТ к дсДНК'},
    {'name': 'Антитела к циклическому цитруллинированному пептиду', 'unit': 'Ед/мл', 'name_en': 'Anti-Cyclic Citrullinated Peptide', 'name_ru': 'Антитела к циклическому цитруллинированному пептиду', 'name_kk': 'Циклді цитрулинденген пептидке антиденелер', 'abbr': 'Anti-CCP,АЦЦП'},
    {'name': 'Компонент комплемента C3', 'unit': 'г/л', 'name_en': 'Complement C3', 'name_ru': 'Компонент комплемента C3', 'name_kk': 'Комплемент компоненті C3', 'abbr': 'C3'},
    {'name': 'Компонент комплемента C4', 'unit': 'г/л', 'name_en': 'Complement C4', 'name_ru': 'Компонент комплемента C4', 'name_kk': 'Комплемент компоненті C4', 'abbr': 'C4'},
    {'name': 'Антинейтрофильные цитоплазматические антитела', 'unit': '', 'name_en': 'ANCA', 'name_ru': 'Антинейтрофильные цитоплазматические антитела', 'name_kk': 'Антинейтрофильді цитоплазмалық антиденелер', 'abbr': 'ANCA,АНЦА'}, # ANCA часто имеет титр и тип (c/p)

    # 7. Tumor Markers / Онкомаркеры / Онкомаркерлер
    {'name': 'Простат-специфический антиген общий', 'unit': 'нг/мл', 'name_en': 'Prostate Specific Antigen, Total', 'name_ru': 'Простат-специфический антиген общий', 'name_kk': 'Простата-спецификалық антиген жалпы', 'abbr': 'PSA,ПСА общий'},
    {'name': 'Простат-специфический антиген свободный', 'unit': 'нг/мл', 'name_en': 'Prostate Specific Antigen, Free', 'name_ru': 'Простат-специфический антиген свободный', 'name_kk': 'Простата-спецификалық антиген бос', 'abbr': 'fPSA,ПСА своб'},
    {'name': 'Раково-эмбриональный антиген', 'unit': 'нг/мл', 'name_en': 'Carcinoembryonic Antigen', 'name_ru': 'Раково-эмбриональный антиген', 'name_kk': 'Рактік-эмбриондық антиген', 'abbr': 'CEA,РЭА'},
    {'name': 'Углеводный антиген 19-9', 'unit': 'Ед/мл', 'name_en': 'Carbohydrate Antigen 19-9', 'name_ru': 'Углеводный антиген 19-9', 'name_kk': 'Көмірсутекті антиген 19-9', 'abbr': 'CA 19-9'},
    {'name': 'Раковый антиген 125', 'unit': 'Ед/мл', 'name_en': 'Cancer Antigen 125', 'name_ru': 'Раковый антиген 125', 'name_kk': 'Рактік антиген 125', 'abbr': 'CA 125'},
    {'name': 'Альфа-фетопротеин', 'unit': 'МЕ/мл', 'name_en': 'Alpha-fetoprotein', 'name_ru': 'Альфа-фетопротеин', 'name_kk': 'Альфа-фетопротеин', 'abbr': 'AFP,АФП'},
    {'name': 'Хорионический гонадотропин человека', 'unit': 'мМЕ/мл', 'name_en': 'Human Chorionic Gonadotropin', 'name_ru': 'Хорионический гонадотропин человека', 'name_kk': 'Адам хориондық гонадотропині', 'abbr': 'hCG,ХГЧ,Бета-ХГЧ'},

    # 8. Toxicology / Drug Monitoring / Токсикология / Лекарственный мониторинг / Токсикология / Дәрілік мониторинг
    {'name': 'Алкоголь в крови', 'unit': 'г/л', 'name_en': 'Blood Alcohol Concentration', 'name_ru': 'Алкоголь в крови', 'name_kk': 'Қандағы алкоголь', 'abbr': 'BAC,Этанол'},
    {'name': 'Парацетамол', 'unit': 'мкг/мл', 'name_en': 'Paracetamol', 'name_ru': 'Парацетамол', 'name_kk': 'Парацетамол', 'abbr': 'Paracetamol,Acetaminophen'},
    {'name': 'Салицилаты', 'unit': 'мг/дл', 'name_en': 'Salicylate', 'name_ru': 'Салицилаты', 'name_kk': 'Салицилаттар', 'abbr': 'Salicylate'},
    {'name': 'Фенитоин', 'unit': 'мкг/мл', 'name_en': 'Phenytoin', 'name_ru': 'Фенитоин', 'name_kk': 'Фенитоин', 'abbr': 'Phenytoin,Дифенин'},
    {'name': 'Дигоксин', 'unit': 'нг/мл', 'name_en': 'Digoxin', 'name_ru': 'Дигоксин', 'name_kk': 'Дигоксин', 'abbr': 'Digoxin'},
    {'name': 'Литий', 'unit': 'ммоль/л', 'name_en': 'Lithium', 'name_ru': 'Литий', 'name_kk': 'Литий', 'abbr': 'Lithium,Li'},
    {'name': 'Вальпроевая кислота', 'unit': 'мкг/мл', 'name_en': 'Valproic Acid', 'name_ru': 'Вальпроевая кислота', 'name_kk': 'Вальпрой қышқылы', 'abbr': 'Valproate,Депакин'},
    {'name': 'Карбамазепин', 'unit': 'мкг/мл', 'name_en': 'Carbamazepine', 'name_ru': 'Карбамазепин', 'name_kk': 'Карбамазепин', 'abbr': 'Carbamazepine,Финлепсин'},
    {'name': 'Ванкомицин', 'unit': 'мкг/мл', 'name_en': 'Vancomycin', 'name_ru': 'Ванкомицин', 'name_kk': 'Ванкомицин', 'abbr': 'Vanco'},
    {'name': 'Гентамицин', 'unit': 'мкг/мл', 'name_en': 'Gentamicin', 'name_ru': 'Гентамицин', 'name_kk': 'Гентамицин', 'abbr': 'Genta'},

    # 9. Miscellaneous / Other Panels / Разное / Прочие панели / Әртүрлі / Басқа панельдер
    {'name': 'Витамин B12', 'unit': 'пг/мл', 'name_en': 'Vitamin B12', 'name_ru': 'Витамин B12', 'name_kk': 'В12 дәрумені', 'abbr': 'Vit B12,Цианокобаламин'},
    {'name': 'Фолиевая кислота', 'unit': 'нг/мл', 'name_en': 'Folate', 'name_ru': 'Фолиевая кислота', 'name_kk': 'Фолий қышқылы', 'abbr': 'Folate,Фолат'},
    {'name': 'Ферритин', 'unit': 'нг/мл', 'name_en': 'Ferritin', 'name_ru': 'Ферритин', 'name_kk': 'Ферритин', 'abbr': 'Ferritin'},
    {'name': 'Железо сывороточное', 'unit': 'мкмоль/л', 'name_en': 'Iron, Serum', 'name_ru': 'Железо сывороточное', 'name_kk': 'Сарысулық темір', 'abbr': 'Fe,Iron'},
    {'name': 'Общая железосвязывающая способность сыворотки', 'unit': 'мкмоль/л', 'name_en': 'Total Iron Binding Capacity', 'name_ru': 'Общая железосвязывающая способность сыворотки', 'name_kk': 'Сарысудың жалпы темір байланыстыру қабілеті', 'abbr': 'TIBC,ОЖСС'},
    {'name': 'Насыщение трансферрина железом', 'unit': '%', 'name_en': 'Transferrin Saturation', 'name_ru': 'Насыщение трансферрина железом', 'name_kk': 'Трансферриннің темірмен қанығуы', 'abbr': 'TSAT,% насыщения трансферрина'},
    {'name': 'Витамин D (25-OH)', 'unit': 'нг/мл', 'name_en': 'Vitamin D (25-OH)', 'name_ru': 'Витамин D (25-OH)', 'name_kk': 'D дәрумені (25-OH)', 'abbr': 'Vit D,25-OH D'},
    {'name': 'Амилаза', 'unit': 'Ед/л', 'name_en': 'Amylase', 'name_ru': 'Амилаза', 'name_kk': 'Амилаза', 'abbr': 'Amylase,AMY'},
    {'name': 'Липаза', 'unit': 'Ед/л', 'name_en': 'Lipase', 'name_ru': 'Липаза', 'name_kk': 'Липаза', 'abbr': 'Lipase,LIP'},
    # Добавьте другие аналиты по мере необходимости
]

def populate_analyte_data(apps, schema_editor):
    """
    Заполняет модель Analyte данными из списка ANALYTES_DATA.
    """
    Analyte = apps.get_model('data', 'Analyte') # Получаем историческую модель
    db_alias = schema_editor.connection.alias

    # Получаем существующие основные имена, чтобы не создавать дубликаты
    existing_names = set(Analyte.objects.using(db_alias).values_list('name', flat=True))

    analytes_to_create = []
    for item in ANALYTES_DATA:
        # Проверяем, существует ли уже аналит с таким основным именем
        if item['name'] not in existing_names:
            analytes_to_create.append(
                Analyte(
                    name=item['name'],
                    unit=item['unit'],
                    name_en=item.get('name_en', ''), # Используем .get для необязательных полей
                    name_ru=item.get('name_ru', ''),
                    name_kk=item.get('name_kk', ''),
                    abbreviations=item.get('abbr', '')
                )
            )
            # Добавляем в множество, чтобы избежать дублирования в этом же списке
            existing_names.add(item['name'])
        else:
            print(f"Analyte '{item['name']}' already exists, skipping.") # Логируем пропуск

    if analytes_to_create:
        print(f"\nCreating {len(analytes_to_create)} new analytes...")
        Analyte.objects.using(db_alias).bulk_create(analytes_to_create)
        print("Analyte data population complete.")
    else:
        print("\nNo new analytes to create.")

def reverse_code(apps, schema_editor):
    """
    При необходимости можно добавить код для отката миграции
    (например, удаление только что добавленных данных),
    но для миграции данных это часто не делается.
    """
    # Analyte = apps.get_model('data', 'Analyte')
    # db_alias = schema_editor.connection.alias
    # names_to_delete = [item['name'] for item in ANALYTES_DATA]
    # Analyte.objects.using(db_alias).filter(name__in=names_to_delete).delete()
    # print(f"\nDeleted analytes added by this migration.")
    pass # Оставляем пустым или добавляем логику отката

class Migration(migrations.Migration):

    # Указываем зависимость от предыдущей миграции в приложении 'data'
    # Замените '0001_initial' на имя вашей *последней* миграции схемы для 'data'
    dependencies = [
        ('data', '0002_initial'), # <-- УБЕДИТЕСЬ, ЧТО ЭТО ИМЯ ВАШЕЙ ПОСЛЕДНЕЙ МИГРАЦИИ СХЕМЫ ДЛЯ data
    ]

    operations = [
        migrations.RunPython(populate_analyte_data, reverse_code=reverse_code),
    ]
