# Generated by Django X.Y on YYYY-MM-DD HH:MM
# -*- coding: utf-8 -*-
from django.db import migrations

# Список данных для аналитов (максимально расширенный для РФ и КЗ)
# ВАЖНО: Проверьте и уточните русские и казахские названия/аббревиатуры!
# Поле 'abbr' содержит варианты через запятую, без пробелов после запятой.
ANALYTES_DATA = [
    # 1. Hematology / Гематология / Гематология
    # CBC / ОАК / ЖҚА
    {'name': 'Гемоглобин', 'unit': 'г/л', 'name_en': 'Hemoglobin', 'name_ru': 'Гемоглобин', 'name_kk': 'Гемоглобин', 'abbr': 'Hb,Hgb,Гб,Гемоглобин (HGB),Гемоглобін,Haemoglobin'},
    {'name': 'Гематокрит', 'unit': '%', 'name_en': 'Hematocrit', 'name_ru': 'Гематокрит', 'name_kk': 'Гематокрит', 'abbr': 'Hct,PCV,Ht,Гематокрит (HCT),Packed Cell Volume'},
    {'name': 'Лейкоциты', 'unit': 'x10^9/л', 'name_en': 'White Blood Cells', 'name_ru': 'Лейкоциты', 'name_kk': 'Лейкоциттер', 'abbr': 'WBC,Leu,Leuko,Лейкоциты (WBC),ЛЕЙК,ЛКЦ,Leukocytes'},
    {'name': 'Эритроциты', 'unit': 'x10^12/л', 'name_en': 'Red Blood Cells', 'name_ru': 'Эритроциты', 'name_kk': 'Эритроциттер', 'abbr': 'RBC,Ery,Эритроциты (RBC),ЭРИТ,ЭР,Erythrocytes'},
    {'name': 'Тромбоциты', 'unit': 'x10^9/л', 'name_en': 'Platelet count', 'name_ru': 'Тромбоциты', 'name_kk': 'Тромбоциттер', 'abbr': 'Plt,Thromb,PLT,Тромбоциты (PLT),ТР,ТРОМБ,Platelets'},
    {'name': 'Средний объем эритроцита', 'unit': 'fL', 'name_en': 'Mean Corpuscular Volume', 'name_ru': 'Средний объем эритроцита', 'name_kk': 'Эритроциттердің орташа көлемі', 'abbr': 'MCV,СОЭр,ЭОК,MCV (средний объем эритроцитов),Ср.объем эритр.'},
    {'name': 'Среднее содержание гемоглобина в эритроците', 'unit': 'пг', 'name_en': 'Mean Corpuscular Hemoglobin', 'name_ru': 'Среднее содержание гемоглобина в эритроците', 'name_kk': 'Эритроциттегі гемоглобиннің орташа мөлшері', 'abbr': 'MCH,МСН (среднее содержание Нb в эритроците),Ср. содерж. Hb в эр-те'},
    {'name': 'Средняя концентрация гемоглобина в эритроците', 'unit': 'г/дл', 'name_en': 'Mean Corpuscular Hemoglobin Concentration', 'name_ru': 'Средняя концентрация гемоглобина в эритроците', 'name_kk': 'Эритроциттегі гемоглобиннің орташа концентрациясы', 'abbr': 'MCHC,МСНС (средняя концентрация Нb в эритроците),Ср. конц. Hb в эр-те'},
    {'name': 'Ширина распределения эритроцитов по объему', 'unit': '%', 'name_en': 'Red Cell Distribution Width (CV)', 'name_ru': 'Ширина распределения эритроцитов по объему', 'name_kk': 'Эритроциттердің көлемі бойынша таралу ені', 'abbr': 'RDW,RDW-CV,RDW CV (ширина распределения эритроцитов),Шир. распр. эритр. по объему,Анизоцитоз эритроцитов'},
    {'name': 'Ширина распределения эритроцитов (ст. откл.)', 'unit': 'fL', 'name_en': 'Red Cell Distribution Width (SD)', 'name_ru': 'Ширина распределения эритроцитов (ст. откл.)', 'name_kk': 'Эритроциттердің таралу ені (ст. ауытқу)', 'abbr': 'RDW-SD'},
    {'name': 'Средний объем тромбоцитов', 'unit': 'фл', 'name_en': 'Mean Platelet Volume', 'name_ru': 'Средний объем тромбоцитов', 'name_kk': 'Тромбоциттердің орташа көлемі', 'abbr': 'MPV,MPV (Средний объем тромбоцитов),Ср. объем тр-тов'},
    {'name': 'Ширина распределения тромбоцитов по объему', 'unit': '%', 'name_en': 'Platelet Distribution Width', 'name_ru': 'Ширина распределения тромбоцитов по объему', 'name_kk': 'Тромбоциттердің көлемі бойынша таралу ені', 'abbr': 'PDW,PDW (Ширина распределения тромбоцитов),Шир. распр. тр-тов,Анизоцитоз тромбоцитов'},
    {'name': 'Коэффициент больших тромбоцитов', 'unit': '%', 'name_en': 'Platelet Large Cell Ratio', 'name_ru': 'Коэффициент больших тромбоцитов', 'name_kk': 'Ірі тромбоциттер коэффициенті', 'abbr': 'P-LCR,P-LCR (Коэффициент больших тромбоцитов),Крупные тромбоциты'},
    {'name': 'Тромбокрит', 'unit': '%', 'name_en': 'Plateletcrit', 'name_ru': 'Тромбокрит', 'name_kk': 'Тромбокрит', 'abbr': 'PCT'},
    {'name': 'Нейтрофилы %', 'unit': '%', 'name_en': 'Neutrophils %', 'name_ru': 'Нейтрофилы %', 'name_kk': 'Нейтрофилдер %', 'abbr': 'NEUT%,NEU%,Нейтрофилы (общее число) %,Нейтрофилы,NEUT,NEU,Сегментоядерные нейтрофилы,Сегментоядерные,с/я,Палочкоядерные нейтрофилы,Палочкоядерные,п/я,Нейтрофильные гранулоциты'},
    {'name': 'Лимфоциты %', 'unit': '%', 'name_en': 'Lymphocytes %', 'name_ru': 'Лимфоциты %', 'name_kk': 'Лимфоциттер %', 'abbr': 'LYMPH%,LYM%,Лимфоциты %,Лимфоциты,LYMPH,LYM,ЛИМФ'},
    {'name': 'Моноциты %', 'unit': '%', 'name_en': 'Monocytes %', 'name_ru': 'Моноциты %', 'name_kk': 'Моноциттер %', 'abbr': 'MONO%,MON%,Моноциты %,Моноциты,MONO,MON,МОН'},
    {'name': 'Эозинофилы %', 'unit': '%', 'name_en': 'Eosinophils %', 'name_ru': 'Эозинофилы %', 'name_kk': 'Эозинофилдер %', 'abbr': 'EOS%,Эозинофилы %,Эозинофилы,EOS,ЭОЗ'},
    {'name': 'Базофилы %', 'unit': '%', 'name_en': 'Basophils %', 'name_ru': 'Базофилы %', 'name_kk': 'Базофилдер %', 'abbr': 'BASO%,Базофилы %,Базофилы,BASO,БАЗ'},
    {'name': 'Нейтрофилы абс.', 'unit': 'x10^9/л', 'name_en': 'Neutrophils abs.', 'name_ru': 'Нейтрофилы абс.', 'name_kk': 'Нейтрофилдер абс.', 'abbr': 'NEUT abs,NEU abs,Нейтрофилы абс.,#NEU,Абсолютное число нейтрофилов'},
    {'name': 'Лимфоциты абс.', 'unit': 'x10^9/л', 'name_en': 'Lymphocytes abs.', 'name_ru': 'Лимфоциты абс.', 'name_kk': 'Лимфоциттер абс.', 'abbr': 'LYMPH abs,LYM abs,Лимфоциты абс.,#LYM,Абсолютное число лимфоцитов'},
    {'name': 'Моноциты абс.', 'unit': 'x10^9/л', 'name_en': 'Monocytes abs.', 'name_ru': 'Моноциты абс.', 'name_kk': 'Моноциттер абс.', 'abbr': 'MONO abs,MON abs,Моноциты абс.,#MON,Абсолютное число моноцитов'},
    {'name': 'Эозинофилы абс.', 'unit': 'x10^9/л', 'name_en': 'Eosinophils abs.', 'name_ru': 'Эозинофилы абс.', 'name_kk': 'Эозинофилдер абс.', 'abbr': 'EOS abs,Эозинофилы абс.,#EOS,Абсолютное число эозинофилов'},
    {'name': 'Базофилы абс.', 'unit': 'x10^9/л', 'name_en': 'Basophils abs.', 'name_ru': 'Базофилы абс.', 'name_kk': 'Базофилдер абс.', 'abbr': 'BASO abs,Базофилы абс.,#BAS,Абсолютное число базофилов'},
    {'name': 'Скорость оседания эритроцитов', 'unit': 'мм/час', 'name_en': 'Erythrocyte Sedimentation Rate', 'name_ru': 'Скорость оседания эритроцитов', 'name_kk': 'Эритроциттердің тұну жылдамдығы', 'abbr': 'ESR,СОЭ,ЭТЖ,СОЭ по Вестергрену,ESR (по Вестергрену),РОЭ'},
    {'name': 'Цветной показатель', 'unit': '', 'name_en': 'Color Index', 'name_ru': 'Цветной показатель', 'name_kk': 'Түстік көрсеткіш', 'abbr': 'ЦП,Цветной показатель,Показатель цветной'},
    {'name': 'Ретикулоциты', 'unit': '%', 'name_en': 'Reticulocytes', 'name_ru': 'Ретикулоциты', 'name_kk': 'Ретикулоциттер', 'abbr': 'Retic,RET,Ретикул.'},
    {'name': 'Ретикулоциты абс.', 'unit': 'x10^9/л', 'name_en': 'Reticulocytes abs.', 'name_ru': 'Ретикулоциты абс.', 'name_kk': 'Ретикулоциттер абс.', 'abbr': '#RET,Ретикулоциты (абс.)'},
    # Coagulation / Коагулограмма / Коагулограмма
    {'name': 'Протромбиновое время', 'unit': 'сек', 'name_en': 'Prothrombin Time', 'name_ru': 'Протромбиновое время', 'name_kk': 'Протромбиндік уақыт', 'abbr': 'PT,ПТВ,ПВ,Протромбин (время)'},
    {'name': 'Протромбин по Квику', 'unit': '%', 'name_en': 'Prothrombin (Quick)', 'name_ru': 'Протромбин по Квику', 'name_kk': 'Квик бойынша протромбин', 'abbr': 'ПТИ,Протромбиновый индекс,Протромбин (индекс),Протромбин %'},
    {'name': 'Международное нормализованное отношение', 'unit': '', 'name_en': 'International Normalized Ratio', 'name_ru': 'Международное нормализованное отношение', 'name_kk': 'Халықаралық қалыптасқан қатынас', 'abbr': 'INR,МНО'},
    {'name': 'Активированное частичное тромбопластиновое время', 'unit': 'сек', 'name_en': 'Activated Partial Thromboplastin Time', 'name_ru': 'Активированное частичное тромбопластиновое время', 'name_kk': 'Белсендірілген ішінара тромбопластиндік уақыт', 'abbr': 'aPTT,АЧТВ,АПТВ'},
    {'name': 'D-димер', 'unit': 'нг/мл', 'name_en': 'D-dimer', 'name_ru': 'D-димер', 'name_kk': 'D-димер', 'abbr': 'D-dimer,D-Dimer'},
    {'name': 'Фибриноген', 'unit': 'г/л', 'name_en': 'Fibrinogen', 'name_ru': 'Фибриноген', 'name_kk': 'Фибриноген', 'abbr': 'Fib,Фибриноген по Клауссу'},
    {'name': 'Тромбиновое время', 'unit': 'сек', 'name_en': 'Thrombin Time', 'name_ru': 'Тромбиновое время', 'name_kk': 'Тромбиндік уақыт', 'abbr': 'TT,ТВ'},
    {'name': 'Антитромбин III', 'unit': '%', 'name_en': 'Antithrombin III', 'name_ru': 'Антитромбин III', 'name_kk': 'Антитромбин III', 'abbr': 'ATIII,АТIII,АТ3'},
    {'name': 'Протеин C', 'unit': '%', 'name_en': 'Protein C', 'name_ru': 'Протеин C', 'name_kk': 'Протеин C', 'abbr': 'Protein C'},
    {'name': 'Протеин S', 'unit': '%', 'name_en': 'Protein S', 'name_ru': 'Протеин S', 'name_kk': 'Протеин S', 'abbr': 'Protein S'},
    {'name': 'Волчаночный антикоагулянт', 'unit': '', 'name_en': 'Lupus Anticoagulant', 'name_ru': 'Волчаночный антикоагулянт', 'name_kk': 'Қасқыр жегі антикоагулянты', 'abbr': 'LA,ВА'},

    # 2. Clinical Biochemistry / Клиническая биохимия / Клиникалық биохимия
    # Renal / Почечные / Бүйрек
    {'name': 'Креатинин', 'unit': 'мкмоль/л', 'name_en': 'Creatinine', 'name_ru': 'Креатинин', 'name_kk': 'Креатинин', 'abbr': 'Crea,Cr,КРЕА,Креатинин сыворотки'},
    {'name': 'Мочевина', 'unit': 'ммоль/л', 'name_en': 'Urea', 'name_ru': 'Мочевина', 'name_kk': 'Несепнәр', 'abbr': 'Urea,МОЧ,Мочевина крови'},
    {'name': 'Азот мочевины крови', 'unit': 'мг/дл', 'name_en': 'Blood Urea Nitrogen', 'name_ru': 'Азот мочевины крови', 'name_kk': 'Қандағы несепнәр азоты', 'abbr': 'BUN'},
    {'name': 'Расчетная скорость клубочковой фильтрации', 'unit': 'мл/мин/1.73м²', 'name_en': 'Estimated Glomerular Filtration Rate', 'name_ru': 'Расчетная скорость клубочковой фильтрации', 'name_kk': 'Болжамды шумақтық фильтрация жылдамдығы', 'abbr': 'eGFR,СКФ,рСКФ,Скорость клубочковой фильтрации,GFR'},
    {'name': 'Мочевая кислота', 'unit': 'мкмоль/л', 'name_en': 'Uric acid', 'name_ru': 'Мочевая кислота', 'name_kk': 'Несеп қышқылы', 'abbr': 'UA,Моч. к-та,Моч.кислота,Мочевая кислота сыворотки'},
    {'name': 'Цистатин C', 'unit': 'мг/л', 'name_en': 'Cystatin C', 'name_ru': 'Цистатин C', 'name_kk': 'Цистатин C', 'abbr': 'CysC,Cystatin C'},
    # LFTs / Печеночные / Бауыр
    {'name': 'Аланинаминотрансфераза', 'unit': 'Ед/л', 'name_en': 'Alanine Aminotransferase', 'name_ru': 'Аланинаминотрансфераза', 'name_kk': 'Аланинаминотрансфераза', 'abbr': 'ALT,АЛТ,АЛаТ,SGPT,АлАТ'},
    {'name': 'Аспартатаминотрансфераза', 'unit': 'Ед/л', 'name_en': 'Aspartate Aminotransferase', 'name_ru': 'Аспартатаминотрансфераза', 'name_kk': 'Аспартатаминотрансфераза', 'abbr': 'AST,АСТ,АСаТ,SGOT,АсАТ'},
    {'name': 'Щелочная фосфатаза', 'unit': 'Ед/л', 'name_en': 'Alkaline Phosphatase', 'name_ru': 'Щелочная фосфатаза', 'name_kk': 'Сілтілік фосфатаза', 'abbr': 'ALP,ЩФ,Щ.Ф.,ALKP,Щелочная фосфатаза общая'},
    {'name': 'Гамма-глутамилтрансфераза', 'unit': 'Ед/л', 'name_en': 'Gamma-glutamyl Transferase', 'name_ru': 'Гамма-глутамилтрансфераза', 'name_kk': 'Гамма-глутамилтрансфераза', 'abbr': 'GGT,ГГТ,ГГТП,Гамма-ГТ'},
    {'name': 'Билирубин общий', 'unit': 'мкмоль/л', 'name_en': 'Bilirubin, Total', 'name_ru': 'Билирубин общий', 'name_kk': 'Жалпы билирубин', 'abbr': 'T Bili,Общий билирубин,Билирубин общ.,БИЛ-О,Билирубин и его фракции'},
    {'name': 'Билирубин прямой', 'unit': 'мкмоль/л', 'name_en': 'Bilirubin, Direct', 'name_ru': 'Билирубин прямой', 'name_kk': 'Тікелей билирубин', 'abbr': 'D Bili,Прямой билирубин,Связанный билирубин,Конъюгированный билирубин,Билирубин пр.,БИЛ-П'},
    {'name': 'Билирубин непрямой', 'unit': 'мкмоль/л', 'name_en': 'Bilirubin, Indirect', 'name_ru': 'Билирубин непрямой', 'name_kk': 'Жанама билирубин', 'abbr': 'I Bili,Непрямой билирубин,Несвязанный билирубин,Свободный билирубин,Билирубин непр.'},
    {'name': 'Альбумин', 'unit': 'г/л', 'name_en': 'Albumin', 'name_ru': 'Альбумин', 'name_kk': 'Альбумин', 'abbr': 'Alb,АЛБ'},
    {'name': 'Общий белок', 'unit': 'г/л', 'name_en': 'Total Protein', 'name_ru': 'Общий белок', 'name_kk': 'Жалпы белок', 'abbr': 'TP,Общ. белок,ОБ,Белок общий'},
    {'name': 'Лактатдегидрогеназа', 'unit': 'Ед/л', 'name_en': 'Lactate Dehydrogenase', 'name_ru': 'Лактатдегидрогеназа', 'name_kk': 'Лактатдегидрогеназа', 'abbr': 'LDH,ЛДГ,ЛДГ общая'},
    {'name': 'Холинэстераза', 'unit': 'Ед/л', 'name_en': 'Cholinesterase', 'name_ru': 'Холинэстераза', 'name_kk': 'Холинэстераза', 'abbr': 'CHE,ХЭ,Псевдохолинэстераза'},
    {'name': 'Аммиак', 'unit': 'мкмоль/л', 'name_en': 'Ammonia', 'name_ru': 'Аммиак', 'name_kk': 'Аммиак', 'abbr': 'Ammonia'},
    # Electrolytes / Электролиты / Электролиттер
    {'name': 'Натрий', 'unit': 'ммоль/л', 'name_en': 'Sodium', 'name_ru': 'Натрий', 'name_kk': 'Натрий', 'abbr': 'Na,Na+'},
    {'name': 'Калий', 'unit': 'ммоль/л', 'name_en': 'Potassium', 'name_ru': 'Калий', 'name_kk': 'Калий', 'abbr': 'K,K+'},
    {'name': 'Хлор', 'unit': 'ммоль/л', 'name_en': 'Chloride', 'name_ru': 'Хлор', 'name_kk': 'Хлор', 'abbr': 'Cl,Cl-'},
    {'name': 'Бикарбонат', 'unit': 'ммоль/л', 'name_en': 'Bicarbonate', 'name_ru': 'Бикарбонат', 'name_kk': 'Бикарбонат', 'abbr': 'HCO3,HCO3-'},
    {'name': 'Общий CO2', 'unit': 'ммоль/л', 'name_en': 'Total CO2', 'name_ru': 'Общий CO2', 'name_kk': 'Жалпы CO2', 'abbr': 'TCO2'},
    {'name': 'Кальций общий', 'unit': 'ммоль/л', 'name_en': 'Calcium, Total', 'name_ru': 'Кальций общий', 'name_kk': 'Жалпы кальций', 'abbr': 'Ca,Общий кальций,Ca общ.'},
    {'name': 'Кальций ионизированный', 'unit': 'ммоль/л', 'name_en': 'Calcium, Ionized', 'name_ru': 'Кальций ионизированный', 'name_kk': 'Иондалған кальций', 'abbr': 'iCa,Ca++,Ca иониз.,Свободный кальций'},
    {'name': 'Магний', 'unit': 'ммоль/л', 'name_en': 'Magnesium', 'name_ru': 'Магний', 'name_kk': 'Магний', 'abbr': 'Mg,Mg++'},
    {'name': 'Фосфор неорганический', 'unit': 'ммоль/л', 'name_en': 'Phosphate', 'name_ru': 'Фосфор неорганический', 'name_kk': 'Бейорганикалық фосфор', 'abbr': 'PO4,Phos,P,Фосфор'},
    # Glucose & Metabolic / Глюкоза и метаболиты / Глюкоза және метаболиттер
    {'name': 'Глюкоза', 'unit': 'ммоль/л', 'name_en': 'Glucose', 'name_ru': 'Глюкоза', 'name_kk': 'Глюкоза', 'abbr': 'Glu,GLU,Глюкоза крови,Сахар крови,Глюкоза плазмы'},
    {'name': 'Гликированный гемоглобин', 'unit': '%', 'name_en': 'Hemoglobin A1c', 'name_ru': 'Гликированный гемоглобин', 'name_kk': 'Гликирленген гемоглобин', 'abbr': 'HbA1c,A1c,Гликозилированный гемоглобин'},
    {'name': 'Пероральный глюкозотолерантный тест', 'unit': 'ммоль/л', 'name_en': 'Oral Glucose Tolerance Test', 'name_ru': 'Пероральный глюкозотолерантный тест', 'name_kk': 'Пероралды глюкозаға төзімділік тесті', 'abbr': 'OGTT,ГТТ,Глюкозотолерантный тест'},
    {'name': 'Лактат', 'unit': 'ммоль/л', 'name_en': 'Lactate', 'name_ru': 'Лактат', 'name_kk': 'Лактат', 'abbr': 'Lactate,Молочная кислота'},
    {'name': 'Фруктозамин', 'unit': 'мкмоль/л', 'name_en': 'Fructosamine', 'name_ru': 'Фруктозамин', 'name_kk': 'Фруктозамин', 'abbr': 'Fructosamine'},
    # Lipid Profile / Липидный профиль / Липидтік профиль
    {'name': 'Холестерин общий', 'unit': 'ммоль/л', 'name_en': 'Total Cholesterol', 'name_ru': 'Холестерин общий', 'name_kk': 'Жалпы холестерин', 'abbr': 'TC,Chol,Общий холестерин,Холестерол,ОХС'},
    {'name': 'Холестерин ЛПНП', 'unit': 'ммоль/л', 'name_en': 'LDL Cholesterol', 'name_ru': 'Холестерин ЛПНП', 'name_kk': 'ТТЛП холестерині', 'abbr': 'LDL,ЛПНП,ЛНП,ХС ЛПНП,Холестерин липопротеинов низкой плотности,Бета-липопротеиды'},
    {'name': 'Холестерин ЛПВП', 'unit': 'ммоль/л', 'name_en': 'HDL Cholesterol', 'name_ru': 'Холестерин ЛПВП', 'name_kk': 'ЖТЛП холестерині', 'abbr': 'HDL,ЛПВП,ЛВП,ХС ЛПВП,Холестерин липопротеинов высокой плотности,Альфа-липопротеиды'},
    {'name': 'Триглицериды', 'unit': 'ммоль/л', 'name_en': 'Triglycerides', 'name_ru': 'Триглицериды', 'name_kk': 'Триглицеридтер', 'abbr': 'TG,Trig,ТГ'},
    {'name': 'Коэффициент атерогенности', 'unit': '', 'name_en': 'Atherogenic Index', 'name_ru': 'Коэффициент атерогенности', 'name_kk': 'Атерогенділік коэффициенті', 'abbr': 'ИА,КА,Индекс атерогенности'},
    {'name': 'Лпопротеин (а)', 'unit': 'мг/дл', 'name_en': 'Lipoprotein (a)', 'name_ru': 'Липопротеин (а)', 'name_kk': 'Липопротеин (а)', 'abbr': 'Lp(a),ЛП(а)'},
    {'name': 'Аполипопротеин А1', 'unit': 'г/л', 'name_en': 'Apolipoprotein A1', 'name_ru': 'Аполипопротеин А1', 'name_kk': 'Аполипопротеин А1', 'abbr': 'ApoA1,АпоА1,Апо А1'},
    {'name': 'Аполипопротеин B', 'unit': 'г/л', 'name_en': 'Apolipoprotein B', 'name_ru': 'Аполипопротеин B', 'name_kk': 'Аполипопротеин B', 'abbr': 'ApoB,АпоВ,Апо B'},
    # Cardiac Enzymes / Сердечные маркеры / Жүрек маркерлері
    {'name': 'Тропонин I', 'unit': 'нг/мл', 'name_en': 'Troponin I', 'name_ru': 'Тропонин I', 'name_kk': 'Тропонин I', 'abbr': 'TnI,cTnI,Тропонин-I'},
    {'name': 'Тропонин T', 'unit': 'нг/мл', 'name_en': 'Troponin T', 'name_ru': 'Тропонин T', 'name_kk': 'Тропонин T', 'abbr': 'TnT,cTnT,Тропонин-Т'},
    {'name': 'Креатинкиназа-МВ', 'unit': 'Ед/л', 'name_en': 'Creatine Kinase-MB', 'name_ru': 'Креатинкиназа-МВ', 'name_kk': 'Креатинкиназа-МВ', 'abbr': 'CK-MB,КФК-МВ,КК-МВ'},
    {'name': 'Креатинкиназа общая', 'unit': 'Ед/л', 'name_en': 'Creatine Kinase, Total', 'name_ru': 'Креатинкиназа общая', 'name_kk': 'Жалпы креатинкиназа', 'abbr': 'CK,КФК,КК,Креатинфосфокиназа'},
    {'name': 'Миоглобин', 'unit': 'нг/мл', 'name_en': 'Myoglobin', 'name_ru': 'Миоглобин', 'name_kk': 'Миоглобин', 'abbr': 'Myo'},
    {'name': 'Натрийуретический пептид B-типа', 'unit': 'пг/мл', 'name_en': 'BNP', 'name_ru': 'Натрийуретический пептид B-типа', 'name_kk': 'B-типті натрийуретикалық пептид', 'abbr': 'BNP,Мозговой натрийуретический пептид'},
    {'name': 'N-концевой пропептид натрийуретического гормона B-типа', 'unit': 'пг/мл', 'name_en': 'NT-proBNP', 'name_ru': 'N-концевой пропептид натрийуретического гормона B-типа', 'name_kk': 'B-типті натрийуретикалық гормонның N-терминалды пропептиді', 'abbr': 'NT-proBNP'},

    # 3. Endocrinology / Hormonal Panel / Эндокринология / Гормоны / Эндокринология / Гормондар
    {'name': 'Тиреотропный гормон', 'unit': 'мМЕ/л', 'name_en': 'Thyroid-Stimulating Hormone', 'name_ru': 'Тиреотропный гормон', 'name_kk': 'Тиреотропты гормон', 'abbr': 'TSH,ТТГ,Тиреотропин'},
    {'name': 'Тироксин свободный', 'unit': 'пмоль/л', 'name_en': 'Free T4', 'name_ru': 'Тироксин свободный', 'name_kk': 'Бос тироксин', 'abbr': 'FT4,св.Т4,Т4 св,Т4 свободный,Free Thyroxine'},
    {'name': 'Трийодтиронин свободный', 'unit': 'пмоль/л', 'name_en': 'Free T3', 'name_ru': 'Трийодтиронин свободный', 'name_kk': 'Бос трийодтиронин', 'abbr': 'FT3,св.Т3,Т3 св,Т3 свободный,Free Triiodothyronine'},
    {'name': 'Тироксин общий', 'unit': 'нмоль/л', 'name_en': 'Total T4', 'name_ru': 'Тироксин общий', 'name_kk': 'Жалпы тироксин', 'abbr': 'T4,Общий Т4,Total Thyroxine'},
    {'name': 'Трийодтиронин общий', 'unit': 'нмоль/л', 'name_en': 'Total T3', 'name_ru': 'Трийодтиронин общий', 'name_kk': 'Жалпы трийодтиронин', 'abbr': 'T3,Общий Т3,Total Triiodothyronine'},
    {'name': 'Антитела к тиреопероксидазе', 'unit': 'МЕ/мл', 'name_en': 'Anti-Thyroid Peroxidase Antibodies', 'name_ru': 'Антитела к тиреопероксидазе', 'name_kk': 'Тиреопероксидазаға антиденелер', 'abbr': 'Anti-TPO,АТ-ТПО,АТПО,АнтиТПО'},
    {'name': 'Антитела к тиреоглобулину', 'unit': 'МЕ/мл', 'name_en': 'Anti-Thyroglobulin Antibodies', 'name_ru': 'Антитела к тиреоглобулину', 'name_kk': 'Тиреоглобулинге антиденелер', 'abbr': 'Anti-TG,АТ-ТГ,АТТГ,АнтиТГ'},
    {'name': 'Антитела к рецепторам ТТГ', 'unit': 'МЕ/л', 'name_en': 'TSH Receptor Antibodies', 'name_ru': 'Антитела к рецепторам ТТГ', 'name_kk': 'ТТГ рецепторларына антиденелер', 'abbr': 'TRAb,АТ-рТТГ,Антитела к рТТГ'},
    {'name': 'Тиреоглобулин', 'unit': 'нг/мл', 'name_en': 'Thyroglobulin', 'name_ru': 'Тиреоглобулин', 'name_kk': 'Тиреоглобулин', 'abbr': 'Tg,ТГ'},
    {'name': 'Кальцитонин', 'unit': 'пг/мл', 'name_en': 'Calcitonin', 'name_ru': 'Кальцитонин', 'name_kk': 'Кальцитонин', 'abbr': 'Calcitonin'},
    {'name': 'Кортизол', 'unit': 'нмоль/л', 'name_en': 'Cortisol', 'name_ru': 'Кортизол', 'name_kk': 'Кортизол', 'abbr': 'Cortisol,Кортизол сыворотки,Гидрокортизон'},
    {'name': 'Кортизол в слюне', 'unit': 'нмоль/л', 'name_en': 'Salivary Cortisol', 'name_ru': 'Кортизол в слюне', 'name_kk': 'Сілекейдегі кортизол', 'abbr': 'Кортизол (слюна)'},
    {'name': 'Кортизол суточной мочи', 'unit': 'нмоль/сут', 'name_en': 'Urinary Free Cortisol', 'name_ru': 'Кортизол суточной мочи', 'name_kk': 'Тәуліктік несептегі кортизол', 'abbr': 'UFC,Свободный кортизол в моче'},
    {'name': 'Адренокортикотропный гормон', 'unit': 'пг/мл', 'name_en': 'Adrenocorticotropic Hormone', 'name_ru': 'Адренокортикотропный гормон', 'name_kk': 'Адренокортикотропты гормон', 'abbr': 'ACTH,АКТГ'},
    {'name': 'Паратгормон', 'unit': 'пг/мл', 'name_en': 'Parathyroid Hormone', 'name_ru': 'Паратгормон', 'name_kk': 'Паратгормон', 'abbr': 'PTH,ПТГ,Паратиреоидный гормон'},
    {'name': 'Тестостерон общий', 'unit': 'нмоль/л', 'name_en': 'Testosterone, Total', 'name_ru': 'Тестостерон общий', 'name_kk': 'Жалпы тестостерон', 'abbr': 'Testo,Общий тестостерон,Тестостерон'},
    {'name': 'Тестостерон свободный', 'unit': 'пг/мл', 'name_en': 'Testosterone, Free', 'name_ru': 'Тестостерон свободный', 'name_kk': 'Бос тестостерон', 'abbr': 'Free Testo,Св. тестостерон,Свободный тестостерон'},
    {'name': 'Глобулин, связывающий половые гормоны', 'unit': 'нмоль/л', 'name_en': 'Sex Hormone Binding Globulin', 'name_ru': 'Глобулин, связывающий половые гормоны', 'name_kk': 'Жыныс гормондарын байланыстыратын глобулин', 'abbr': 'SHBG,ГСПГ,СССГ'},
    {'name': 'Эстрадиол', 'unit': 'пмоль/л', 'name_en': 'Estradiol', 'name_ru': 'Эстрадиол', 'name_kk': 'Эстрадиол', 'abbr': 'E2'},
    {'name': 'Прогестерон', 'unit': 'нмоль/л', 'name_en': 'Progesterone', 'name_ru': 'Прогестерон', 'name_kk': 'Прогестерон', 'abbr': 'Progesterone,ПРГ'},
    {'name': 'Лютеинизирующий гормон', 'unit': 'МЕ/л', 'name_en': 'Luteinizing Hormone', 'name_ru': 'Лютеинизирующий гормон', 'name_kk': 'Лютеиндеуші гормон', 'abbr': 'LH,ЛГ'},
    {'name': 'Фолликулостимулирующий гормон', 'unit': 'МЕ/л', 'name_en': 'Follicle-Stimulating Hormone', 'name_ru': 'Фолликулостимулирующий гормон', 'name_kk': 'Фолликул стимулдаушы гормон', 'abbr': 'FSH,ФСГ'},
    {'name': 'Пролактин', 'unit': 'мМЕ/л', 'name_en': 'Prolactin', 'name_ru': 'Пролактин', 'name_kk': 'Пролактин', 'abbr': 'PRL,ПРЛ'},
    {'name': 'Инсулин', 'unit': 'мкМЕ/мл', 'name_en': 'Insulin', 'name_ru': 'Инсулин', 'name_kk': 'Инсулин', 'abbr': 'Insulin'},
    {'name': 'C-пептид', 'unit': 'нг/мл', 'name_en': 'C-peptide', 'name_ru': 'C-пептид', 'name_kk': 'C-пептид', 'abbr': 'C-peptide'},
    {'name': 'ДГЭА-Сульфат', 'unit': 'мкмоль/л', 'name_en': 'DHEA-Sulfate', 'name_ru': 'ДГЭА-Сульфат', 'name_kk': 'ДГЭА-Сульфат', 'abbr': 'DHEA-S,ДГЭА-С,ДЭА-SO4,Дегидроэпиандростерон-сульфат'},
    {'name': 'Альдостерон', 'unit': 'пг/мл', 'name_en': 'Aldosterone', 'name_ru': 'Альдостерон', 'name_kk': 'Альдостерон', 'abbr': 'Aldosterone'},
    {'name': 'Ренин', 'unit': 'мкМЕ/мл', 'name_en': 'Renin', 'name_ru': 'Ренин', 'name_kk': 'Ренин', 'abbr': 'Renin,Активность ренина плазмы,АРП'},
    {'name': 'Соматотропный гормон', 'unit': 'нг/мл', 'name_en': 'Growth Hormone', 'name_ru': 'Соматотропный гормон', 'name_kk': 'Соматотропты гормон', 'abbr': 'GH,СТГ,Гормон роста'},
    {'name': 'Инсулиноподобный фактор роста 1', 'unit': 'нг/мл', 'name_en': 'Insulin-like Growth Factor 1', 'name_ru': 'Инсулиноподобный фактор роста 1', 'name_kk': 'Инсулин тәрізді өсу факторы 1', 'abbr': 'IGF-1,ИФР-1,Соматомедин С'},
    {'name': 'Антимюллеров гормон', 'unit': 'нг/мл', 'name_en': 'Anti-Mullerian Hormone', 'name_ru': 'Антимюллеров гормон', 'name_kk': 'Антимюллерлік гормон', 'abbr': 'AMH,АМГ'},
    {'name': '17-ОН-прогестерон', 'unit': 'нмоль/л', 'name_en': '17-Hydroxyprogesterone', 'name_ru': '17-ОН-прогестерон', 'name_kk': '17-ОН-прогестерон', 'abbr': '17-OHP,17-ОПГ'},
    {'name': 'Андростендион', 'unit': 'нг/мл', 'name_en': 'Androstenedione', 'name_ru': 'Андростендион', 'name_kk': 'Андростендион', 'abbr': 'Androstenedione'},

    # 4. Infectious Disease Testing / Инфекционные заболевания / Инфекциялық аурулар
    {'name': 'HBsAg', 'unit': '', 'name_en': 'Hepatitis B Surface Antigen', 'name_ru': 'HBs-антиген', 'name_kk': 'HBs-антиген', 'abbr': 'HBsAg,Поверхностный антиген вируса гепатита B,Австралийский антиген'},
    {'name': 'Anti-HBc Total', 'unit': '', 'name_en': 'Hepatitis B Core Antibody (Total)', 'name_ru': 'Anti-HBc общие', 'name_kk': 'Anti-HBc жалпы', 'abbr': 'Anti-HBc,HBcAb,Антитела к ядерному антигену гепатита B,Антитела к core-антигену гепатита B'},
    {'name': 'Anti-HBc IgM', 'unit': '', 'name_en': 'Hepatitis B Core Antibody (IgM)', 'name_ru': 'Anti-HBc IgM', 'name_kk': 'Anti-HBc IgM', 'abbr': 'Anti-HBc IgM,HBcAb IgM'},
    {'name': 'Anti-HBs', 'unit': 'МЕ/л', 'name_en': 'Hepatitis B Surface Antibody', 'name_ru': 'Anti-HBs', 'name_kk': 'Anti-HBs', 'abbr': 'Anti-HBs,HBsAb,Антитела к поверхностному антигену гепатита B'},
    {'name': 'HBeAg', 'unit': '', 'name_en': 'Hepatitis B e-Antigen', 'name_ru': 'HBe-антиген', 'name_kk': 'HBe-антиген', 'abbr': 'HBeAg'},
    {'name': 'Anti-HBe', 'unit': '', 'name_en': 'Hepatitis B e-Antibody', 'name_ru': 'Anti-HBe', 'name_kk': 'Anti-HBe', 'abbr': 'Anti-HBe,HBeAb'},
    {'name': 'Anti-HCV Total', 'unit': '', 'name_en': 'Hepatitis C Antibody', 'name_ru': 'Anti-HCV общие', 'name_kk': 'Anti-HCV жалпы', 'abbr': 'Anti-HCV,HCVAb,Антитела к вирусу гепатита C,Анти-ВГС'},
    {'name': 'ВИЧ (антитела и антиген)', 'unit': '', 'name_en': 'HIV 1/2 Antibody/Antigen', 'name_ru': 'ВИЧ (антитела и антиген)', 'name_kk': 'АИТВ (антиденелер және антиген)', 'abbr': 'HIV Ag/Ab,ВИЧ 1/2,ВИЧ-комбо,HIV 1/2 Ag+Ab,Антитела к ВИЧ 1 и 2 и антиген ВИЧ 1 и 2'},
    {'name': 'Сифилис RPR', 'unit': '', 'name_en': 'Syphilis Test (RPR)', 'name_ru': 'Сифилис RPR', 'name_kk': 'Мерез RPR', 'abbr': 'RPR,RW,Реакция Вассермана,Кардиолипиновый тест,VDRL,Микрореакция преципитации,МРП'},
    {'name': 'Сифилис TPHA', 'unit': '', 'name_en': 'Syphilis Confirmatory (TPHA)', 'name_ru': 'Сифилис TPHA', 'name_kk': 'Мерез TPHA', 'abbr': 'TPHA,РПГА,Реакция пассивной гемагглютинации,ИФА на сифилис'},
    {'name': 'Сифилис IgM/IgG', 'unit': '', 'name_en': 'Syphilis IgM/IgG', 'name_ru': 'Сифилис IgM/IgG', 'name_kk': 'Мерез IgM/IgG', 'abbr': 'Сифилис (IgM + IgG),Treponema pallidum антитела,Антитела к Treponema pallidum суммарные'},
    {'name': 'COVID-19 (ПЦР)', 'unit': '', 'name_en': 'COVID-19 PCR', 'name_ru': 'COVID-19 (ПЦР)', 'name_kk': 'COVID-19 (ПТР)', 'abbr': 'COVID PCR,SARS-CoV-2 РНК,ПЦР на ковид,РНК SARS-CoV-2'},
    {'name': 'COVID-19 (Антиген)', 'unit': '', 'name_en': 'COVID-19 Antigen', 'name_ru': 'COVID-19 (Антиген)', 'name_kk': 'COVID-19 (Антиген)', 'abbr': 'COVID Ag,Антиген SARS-CoV-2'},
    {'name': 'COVID-19 Антитела IgG', 'unit': '', 'name_en': 'COVID-19 Antibody IgG', 'name_ru': 'COVID-19 Антитела IgG', 'name_kk': 'COVID-19 Антиденелер IgG', 'abbr': 'COVID IgG,Anti-SARS-CoV-2 IgG,Антитела IgG к SARS-CoV-2,Антитела к S-белку IgG'},
    {'name': 'COVID-19 Антитела IgM', 'unit': '', 'name_en': 'COVID-19 Antibody IgM', 'name_ru': 'COVID-19 Антитела IgM', 'name_kk': 'COVID-19 Антиденелер IgM', 'abbr': 'COVID IgM,Anti-SARS-CoV-2 IgM,Антитела IgM к SARS-CoV-2'},
    {'name': 'Грипп A/B', 'unit': '', 'name_en': 'Influenza A/B', 'name_ru': 'Грипп A/B', 'name_kk': 'Тұмау A/B', 'abbr': 'Flu A/B,Грипп А+В'},
    {'name': 'Вирус Эпштейна-Барр VCA IgG', 'unit': '', 'name_en': 'Epstein-Barr Virus VCA IgG', 'name_ru': 'Вирус Эпштейна-Барр VCA IgG', 'name_kk': 'Эпштейн-Барр вирусы VCA IgG', 'abbr': 'EBV VCA IgG,ВЭБ VCA IgG,Антитела IgG к капсидному антигену ВЭБ'},
    {'name': 'Вирус Эпштейна-Барр VCA IgM', 'unit': '', 'name_en': 'Epstein-Barr Virus VCA IgM', 'name_ru': 'Вирус Эпштейна-Барр VCA IgM', 'name_kk': 'Эпштейн-Барр вирусы VCA IgM', 'abbr': 'EBV VCA IgM,ВЭБ VCA IgM,Антитела IgM к капсидному антигену ВЭБ'},
    {'name': 'Вирус Эпштейна-Барр EA IgG', 'unit': '', 'name_en': 'Epstein-Barr Virus EA IgG', 'name_ru': 'Вирус Эпштейна-Барр EA IgG', 'name_kk': 'Эпштейн-Барр вирусы EA IgG', 'abbr': 'EBV EA IgG,ВЭБ EA IgG,Антитела IgG к раннему антигену ВЭБ'},
    {'name': 'Вирус Эпштейна-Барр EBNA IgG', 'unit': '', 'name_en': 'Epstein-Barr Virus EBNA IgG', 'name_ru': 'Вирус Эпштейна-Барр EBNA IgG', 'name_kk': 'Эпштейн-Барр вирусы EBNA IgG', 'abbr': 'EBV EBNA IgG,ВЭБ EBNA IgG,Антитела IgG к ядерному антигену ВЭБ'},
    {'name': 'Цитомегаловирус IgG', 'unit': '', 'name_en': 'Cytomegalovirus IgG', 'name_ru': 'Цитомегаловирус IgG', 'name_kk': 'Цитомегаловирус IgG', 'abbr': 'CMV IgG,ЦМВ IgG,Антитела IgG к ЦМВ'},
    {'name': 'Цитомегаловирус IgM', 'unit': '', 'name_en': 'Cytomegalovirus IgM', 'name_ru': 'Цитомегаловирус IgM', 'name_kk': 'Цитомегаловирус IgM', 'abbr': 'CMV IgM,ЦМВ IgM,Антитела IgM к ЦМВ'},
    {'name': 'Вирус простого герпеса 1/2 IgG', 'unit': '', 'name_en': 'Herpes Simplex Virus 1/2 IgG', 'name_ru': 'Вирус простого герпеса 1/2 IgG', 'name_kk': 'Жай герпес вирусы 1/2 IgG', 'abbr': 'HSV 1/2 IgG,ВПГ 1/2 IgG,Антитела IgG к ВПГ 1 и 2 типов'},
    {'name': 'Вирус простого герпеса 1/2 IgM', 'unit': '', 'name_en': 'Herpes Simplex Virus 1/2 IgM', 'name_ru': 'Вирус простого герпеса 1/2 IgM', 'name_kk': 'Жай герпес вирусы 1/2 IgM', 'abbr': 'HSV 1/2 IgM,ВПГ 1/2 IgM,Антитела IgM к ВПГ 1 и 2 типов'},
    {'name': 'Токсоплазма IgG', 'unit': 'МЕ/мл', 'name_en': 'Toxoplasma gondii IgG', 'name_ru': 'Токсоплазма IgG', 'name_kk': 'Токсоплазма IgG', 'abbr': 'Toxo IgG,Антитела IgG к Toxoplasma gondii'},
    {'name': 'Токсоплазма IgM', 'unit': '', 'name_en': 'Toxoplasma gondii IgM', 'name_ru': 'Токсоплазма IgM', 'name_kk': 'Токсоплазма IgM', 'abbr': 'Toxo IgM,Антитела IgM к Toxoplasma gondii'},
    {'name': 'Краснуха IgG', 'unit': 'МЕ/мл', 'name_en': 'Rubella IgG', 'name_ru': 'Краснуха IgG', 'name_kk': 'Қызылша IgG', 'abbr': 'Rubella IgG,Антитела IgG к вирусу краснухи'},
    {'name': 'Краснуха IgM', 'unit': '', 'name_en': 'Rubella IgM', 'name_ru': 'Краснуха IgM', 'name_kk': 'Қызылша IgM', 'abbr': 'Rubella IgM,Антитела IgM к вирусу краснухи'},
    {'name': 'Квантифероновый тест', 'unit': 'МЕ/мл', 'name_en': 'Tuberculosis Test (Quantiferon)', 'name_ru': 'Квантифероновый тест', 'name_kk': 'Квантиферондық тест', 'abbr': 'QFT,IGRA,Т-Спот,T-SPOT.TB'},
    {'name': 'Проба Манту', 'unit': 'мм', 'name_en': 'Tuberculosis Test (Mantoux)', 'name_ru': 'Проба Манту', 'name_kk': 'Манту сынамасы', 'abbr': 'PPD,Манту,Реакция Манту'},
    {'name': 'Диаскинтест', 'unit': 'мм', 'name_en': 'Diaskintest', 'name_ru': 'Диаскинтест', 'name_kk': 'Диаскинтест', 'abbr': 'Diaskintest'},
    {'name': 'Хламидия трахоматис IgG', 'unit': '', 'name_en': 'Chlamydia trachomatis IgG', 'name_ru': 'Хламидия трахоматис IgG', 'name_kk': 'Хламидия трахоматис IgG', 'abbr': 'Chlamydia IgG,Антитела IgG к Chlamydia trachomatis'},
    {'name': 'Хламидия трахоматис IgA', 'unit': '', 'name_en': 'Chlamydia trachomatis IgA', 'name_ru': 'Хламидия трахоматис IgA', 'name_kk': 'Хламидия трахоматис IgA', 'abbr': 'Chlamydia IgA,Антитела IgA к Chlamydia trachomatis'},
    {'name': 'Хламидия трахоматис IgM', 'unit': '', 'name_en': 'Chlamydia trachomatis IgM', 'name_ru': 'Хламидия трахоматис IgM', 'name_kk': 'Хламидия трахоматис IgM', 'abbr': 'Chlamydia IgM,Антитела IgM к Chlamydia trachomatis'},
    {'name': 'Микоплазма пневмонии IgG', 'unit': '', 'name_en': 'Mycoplasma pneumoniae IgG', 'name_ru': 'Микоплазма пневмонии IgG', 'name_kk': 'Микоплазма пневмонии IgG', 'abbr': 'Mycoplasma IgG,Антитела IgG к Mycoplasma pneumoniae'},
    {'name': 'Микоплазма пневмонии IgM', 'unit': '', 'name_en': 'Mycoplasma pneumoniae IgM', 'name_ru': 'Микоплазма пневмонии IgM', 'name_kk': 'Микоплазма пневмонии IgM', 'abbr': 'Mycoplasma IgM,Антитела IgM к Mycoplasma pneumoniae'},
    {'name': 'Helicobacter pylori IgG', 'unit': '', 'name_en': 'Helicobacter pylori IgG', 'name_ru': 'Helicobacter pylori IgG', 'name_kk': 'Helicobacter pylori IgG', 'abbr': 'H.pylori IgG,Антитела IgG к Helicobacter pylori'},
    {'name': 'Helicobacter pylori IgA', 'unit': '', 'name_en': 'Helicobacter pylori IgA', 'name_ru': 'Helicobacter pylori IgA', 'name_kk': 'Helicobacter pylori IgA', 'abbr': 'H.pylori IgA,Антитела IgA к Helicobacter pylori'},
    {'name': 'Helicobacter pylori IgM', 'unit': '', 'name_en': 'Helicobacter pylori IgM', 'name_ru': 'Helicobacter pylori IgM', 'name_kk': 'Helicobacter pylori IgM', 'abbr': 'H.pylori IgM,Антитела IgM к Helicobacter pylori'},
    {'name': 'Антитела к лямблиям суммарные', 'unit': '', 'name_en': 'Giardia lamblia Antibodies (Total)', 'name_ru': 'Антитела к лямблиям суммарные', 'name_kk': 'Лямблияларға антиденелер (жиынтық)', 'abbr': 'Anti-Giardia Total,Антитела к Giardia lamblia'},
    {'name': 'Антитела к аскаридам IgG', 'unit': '', 'name_en': 'Ascaris lumbricoides IgG', 'name_ru': 'Антитела к аскаридам IgG', 'name_kk': 'Аскаридаларға антиденелер IgG', 'abbr': 'Anti-Ascaris IgG,Антитела IgG к Ascaris lumbricoides'},
    {'name': 'Антитела к токсокарам IgG', 'unit': '', 'name_en': 'Toxocara canis IgG', 'name_ru': 'Антитела к токсокарам IgG', 'name_kk': 'Токсокараларға антиденелер IgG', 'abbr': 'Anti-Toxocara IgG,Антитела IgG к Toxocara canis'},
    {'name': 'Антитела к эхинококку IgG', 'unit': '', 'name_en': 'Echinococcus granulosus IgG', 'name_ru': 'Антитела к эхинококку IgG', 'name_kk': 'Эхинококкқа антиденелер IgG', 'abbr': 'Anti-Echinococcus IgG,Антитела IgG к Echinococcus granulosus'},
    {'name': 'Антитела к описторхам IgG', 'unit': '', 'name_en': 'Opisthorchis felineus IgG', 'name_ru': 'Антитела к описторхам IgG', 'name_kk': 'Описторхтарға антиденелер IgG', 'abbr': 'Anti-Opisthorchis IgG,Антитела IgG к Opisthorchis felineus'},

    # 5. Urinalysis / Общий анализ мочи / Жалпы несеп анализі
    {'name': 'Цвет мочи', 'unit': '', 'name_en': 'Urine Color', 'name_ru': 'Цвет мочи', 'name_kk': 'Несеп түсі', 'abbr': 'Color,Цвет,COL'},
    {'name': 'Прозрачность мочи', 'unit': '', 'name_en': 'Urine Clarity', 'name_ru': 'Прозрачность мочи', 'name_kk': 'Несеп мөлдірлігі', 'abbr': 'Clarity,Прозрачность,CLA'},
    {'name': 'pH мочи', 'unit': '', 'name_en': 'Urine pH', 'name_ru': 'pH мочи', 'name_kk': 'Несеп рН', 'abbr': 'pH,Реакция'},
    {'name': 'Удельный вес мочи', 'unit': '', 'name_en': 'Urine Specific Gravity', 'name_ru': 'Удельный вес мочи', 'name_kk': 'Несептің меншікті салмағы', 'abbr': 'SG,Уд.вес,УВ,Относительная плотность'},
    {'name': 'Белок в моче', 'unit': 'г/л', 'name_en': 'Urine Protein', 'name_ru': 'Белок в моче', 'name_kk': 'Несептегі белок', 'abbr': 'Protein,PRO,Белок,БЕЛОК'},
    {'name': 'Глюкоза в моче', 'unit': '', 'name_en': 'Urine Glucose', 'name_ru': 'Глюкоза в моче', 'name_kk': 'Несептегі глюкоза', 'abbr': 'Glucose,GLU,Сахар,ГЛЮ'},
    {'name': 'Кетоны в моче', 'unit': '', 'name_en': 'Urine Ketones', 'name_ru': 'Кетоны в моче', 'name_kk': 'Несептегі кетондар', 'abbr': 'Ketones,KET,Кетоновые тела,Ацетон'},
    {'name': 'Кровь в моче', 'unit': '', 'name_en': 'Urine Blood', 'name_ru': 'Кровь в моче', 'name_kk': 'Несептегі қан', 'abbr': 'Blood,BLD,Эритроциты (хим),Гемоглобин (хим)'},
    {'name': 'Билирубин в моче', 'unit': '', 'name_en': 'Urine Bilirubin', 'name_ru': 'Билирубин в моче', 'name_kk': 'Несептегі билирубин', 'abbr': 'Bilirubin,BIL,БИЛ'},
    {'name': 'Уробилиноген в моче', 'unit': '', 'name_en': 'Urine Urobilinogen', 'name_ru': 'Уробилиноген в моче', 'name_kk': 'Несептегі уробилиноген', 'abbr': 'Urobilinogen,URO,УБГ'},
    {'name': 'Нитриты в моче', 'unit': '', 'name_en': 'Urine Nitrite', 'name_ru': 'Нитриты в моче', 'name_kk': 'Несептегі нитриттер', 'abbr': 'Nitrite,NIT,НИТ'},
    {'name': 'Лейкоциты в моче (эстераза)', 'unit': '', 'name_en': 'Urine Leukocyte Esterase', 'name_ru': 'Лейкоцитарная эстераза', 'name_kk': 'Лейкоцитарлық эстераза', 'abbr': 'LEU,Лейкоциты (хим),ЛЕЙ'},
    {'name': 'Эритроциты в моче (микроскопия)', 'unit': 'в п/з', 'name_en': 'Urine Red Blood Cells (micro)', 'name_ru': 'Эритроциты (микроскопия)', 'name_kk': 'Эритроциттер (микроскопия)', 'abbr': 'RBC mic,Эритроциты'},
    {'name': 'Лейкоциты в моче (микроскопия)', 'unit': 'в п/з', 'name_en': 'Urine White Blood Cells (micro)', 'name_ru': 'Лейкоциты (микроскопия)', 'name_kk': 'Лейкоциттер (микроскопия)', 'abbr': 'WBC mic,Лейкоциты'},
    {'name': 'Эпителий плоский', 'unit': 'в п/з', 'name_en': 'Squamous Epithelial Cells', 'name_ru': 'Эпителий плоский', 'name_kk': 'Жалпақ эпителий', 'abbr': 'Epith,Эпит. пл.,Эпителий'},
    {'name': 'Эпителий переходный', 'unit': 'в п/з', 'name_en': 'Transitional Epithelial Cells', 'name_ru': 'Эпителий переходный', 'name_kk': 'Ауыспалы эпителий', 'abbr': 'Эпит. пер.'},
    {'name': 'Эпителий почечный', 'unit': 'в п/з', 'name_en': 'Renal Epithelial Cells', 'name_ru': 'Эпителий почечный', 'name_kk': 'Бүйрек эпителийі', 'abbr': 'Эпит. поч.'},
    {'name': 'Цилиндры гиалиновые', 'unit': 'в п/з', 'name_en': 'Hyaline Casts', 'name_ru': 'Цилиндры гиалиновые', 'name_kk': 'Гиалинді цилиндрлер', 'abbr': 'Casts hyal,Цил. гиал.'},
    {'name': 'Цилиндры зернистые', 'unit': 'в п/з', 'name_en': 'Granular Casts', 'name_ru': 'Цилиндры зернистые', 'name_kk': 'Дәнді цилиндрлер', 'abbr': 'Casts gran,Цил. зерн.'},
    {'name': 'Цилиндры восковидные', 'unit': 'в п/з', 'name_en': 'Waxy Casts', 'name_ru': 'Цилиндры восковидные', 'name_kk': 'Балауызды цилиндрлер', 'abbr': 'Casts waxy,Цил. воск.'},
    {'name': 'Цилиндры эритроцитарные', 'unit': 'в п/з', 'name_en': 'RBC Casts', 'name_ru': 'Цилиндры эритроцитарные', 'name_kk': 'Эритроцитарлық цилиндрлер', 'abbr': 'Casts RBC,Цил. эритр.'},
    {'name': 'Цилиндры лейкоцитарные', 'unit': 'в п/з', 'name_en': 'WBC Casts', 'name_ru': 'Цилиндры лейкоцитарные', 'name_kk': 'Лейкоцитарлық цилиндрлер', 'abbr': 'Casts WBC,Цил. лейк.'},
    {'name': 'Кристаллы в моче', 'unit': '', 'name_en': 'Urine Crystals', 'name_ru': 'Кристаллы в моче', 'name_kk': 'Несептегі кристалдар', 'abbr': 'Crystals,Кристаллы,Соли'},
    {'name': 'Бактерии в моче', 'unit': '', 'name_en': 'Urine Bacteria', 'name_ru': 'Бактерии в моче', 'name_kk': 'Несептегі бактериялар', 'abbr': 'Bacteria,Бактерии,БАКТ'},
    {'name': 'Слизь в моче', 'unit': '', 'name_en': 'Urine Mucus', 'name_ru': 'Слизь в моче', 'name_kk': 'Несептегі шырыш', 'abbr': 'Mucus,Слизь'},
    {'name': 'Соотношение Белок/Креатинин в моче', 'unit': 'мг/г', 'name_en': 'Urine Protein-to-Creatinine Ratio', 'name_ru': 'Соотношение Белок/Креатинин в моче', 'name_kk': 'Несептегі Белок/Креатинин қатынасы', 'abbr': 'UPCR,Соотношение белок/креатинин'},
    {'name': 'Суточный белок в моче', 'unit': 'г/сут', 'name_en': '24-hour Urine Protein', 'name_ru': 'Суточный белок в моче', 'name_kk': 'Тәуліктік несептегі белок', 'abbr': '24h Protein,Белок суточной мочи'},
    {'name': 'Анализ мочи по Нечипоренко (Лейкоциты)', 'unit': 'в 1 мл', 'name_en': 'Nechiporenko Urine Test (WBC)', 'name_ru': 'Анализ мочи по Нечипоренко (Лейкоциты)', 'name_kk': 'Нечипоренко бойынша несеп анализі (Лейкоциттер)', 'abbr': 'Нечипоренко лейк.'},
    {'name': 'Анализ мочи по Нечипоренко (Эритроциты)', 'unit': 'в 1 мл', 'name_en': 'Nechiporenko Urine Test (RBC)', 'name_ru': 'Анализ мочи по Нечипоренко (Эритроциты)', 'name_kk': 'Нечипоренко бойынша несеп анализі (Эритроциттер)', 'abbr': 'Нечипоренко эритр.'},
    {'name': 'Анализ мочи по Нечипоренко (Цилиндры)', 'unit': 'в 1 мл', 'name_en': 'Nechiporenko Urine Test (Casts)', 'name_ru': 'Анализ мочи по Нечипоренко (Цилиндры)', 'name_kk': 'Нечипоренко бойынша несеп анализі (Цилиндрлер)', 'abbr': 'Нечипоренко цил.'},

    # 6. Immunology / Autoimmune Panels / Иммунология / Аутоиммунные панели / Иммунология / Аутоиммунды панельдер
    {'name': 'С-реактивный белок', 'unit': 'мг/л', 'name_en': 'C-Reactive Protein', 'name_ru': 'С-реактивный белок', 'name_kk': 'С-реактивті белок', 'abbr': 'CRP,СРБ,ЦРБ'},
    {'name': 'Скорость оседания эритроцитов', 'unit': 'мм/час', 'name_en': 'Erythrocyte Sedimentation Rate', 'name_ru': 'Скорость оседания эритроцитов', 'name_kk': 'Эритроциттердің тұну жылдамдығы', 'abbr': 'ESR,СОЭ,ЭТЖ,СОЭ по Вестергрену,ESR (по Вестергрену),РОЭ'},
    {'name': 'Ревматоидный фактор', 'unit': 'МЕ/мл', 'name_en': 'Rheumatoid Factor', 'name_ru': 'Ревматоидный фактор', 'name_kk': 'Ревматоидты фактор', 'abbr': 'RF,РФ'},
    {'name': 'Антистрептолизин-О', 'unit': 'МЕ/мл', 'name_en': 'Anti-Streptolysin O', 'name_ru': 'Антистрептолизин-О', 'name_kk': 'Антистрептолизин-О', 'abbr': 'ASO,АСЛ-О,АСЛО'},
    {'name': 'Антинуклеарный фактор', 'unit': '', 'name_en': 'Anti-Nuclear Antibody', 'name_ru': 'Антинуклеарный фактор', 'name_kk': 'Антинуклеарлы фактор', 'abbr': 'ANA,АНФ,АНА'},
    {'name': 'Антитела к дсДНК', 'unit': 'МЕ/мл', 'name_en': 'Anti-dsDNA Antibody', 'name_ru': 'Антитела к двуспиральной ДНК', 'name_kk': 'Қос спиральды ДНҚ-ға антиденелер', 'abbr': 'Anti-dsDNA,АТ к дсДНК,anti-DNA'},
    {'name': 'Антитела к циклическому цитруллинированному пептиду', 'unit': 'Ед/мл', 'name_en': 'Anti-Cyclic Citrullinated Peptide', 'name_ru': 'Антитела к циклическому цитруллинированному пептиду', 'name_kk': 'Циклді цитрулинденген пептидке антиденелер', 'abbr': 'Anti-CCP,АЦЦП,Анти-ЦЦП'},
    {'name': 'Компонент комплемента C3', 'unit': 'г/л', 'name_en': 'Complement C3', 'name_ru': 'Компонент комплемента C3', 'name_kk': 'Комплемент компоненті C3', 'abbr': 'C3'},
    {'name': 'Компонент комплемента C4', 'unit': 'г/л', 'name_en': 'Complement C4', 'name_ru': 'Компонент комплемента C4', 'name_kk': 'Комплемент компоненті C4', 'abbr': 'C4'},
    {'name': 'Антинейтрофильные цитоплазматические антитела', 'unit': '', 'name_en': 'ANCA', 'name_ru': 'Антинейтрофильные цитоплазматические антитела', 'name_kk': 'Антинейтрофильді цитоплазмалық антиденелер', 'abbr': 'ANCA,АНЦА'},
    {'name': 'Иммуноглобулин A', 'unit': 'г/л', 'name_en': 'Immunoglobulin A', 'name_ru': 'Иммуноглобулин A', 'name_kk': 'Иммуноглобулин A', 'abbr': 'IgA'},
    {'name': 'Иммуноглобулин M', 'unit': 'г/л', 'name_en': 'Immunoglobulin M', 'name_ru': 'Иммуноглобулин M', 'name_kk': 'Иммуноглобулин M', 'abbr': 'IgM'},
    {'name': 'Иммуноглобулин G', 'unit': 'г/л', 'name_en': 'Immunoglobulin G', 'name_ru': 'Иммуноглобулин G', 'name_kk': 'Иммуноглобулин G', 'abbr': 'IgG'},
    {'name': 'Иммуноглобулин E', 'unit': 'МЕ/мл', 'name_en': 'Immunoglobulin E', 'name_ru': 'Иммуноглобулин E', 'name_kk': 'Иммуноглобулин E', 'abbr': 'IgE,Общий IgE'},
    {'name': 'Криоглобулины', 'unit': '', 'name_en': 'Cryoglobulins', 'name_ru': 'Криоглобулины', 'name_kk': 'Криоглобулиндер', 'abbr': 'Cryoglobulins'},
    {'name': 'Антитела к кардиолипину IgG', 'unit': 'Ед/мл', 'name_en': 'Anti-Cardiolipin IgG', 'name_ru': 'Антитела к кардиолипину IgG', 'name_kk': 'Кардиолипинге антиденелер IgG', 'abbr': 'aCL IgG'},
    {'name': 'Антитела к кардиолипину IgM', 'unit': 'Ед/мл', 'name_en': 'Anti-Cardiolipin IgM', 'name_ru': 'Антитела к кардиолипину IgM', 'name_kk': 'Кардиолипинге антиденелер IgM', 'abbr': 'aCL IgM'},
    {'name': 'Антитела к бета-2-гликопротеину I IgG', 'unit': 'Ед/мл', 'name_en': 'Anti-Beta-2-Glycoprotein I IgG', 'name_ru': 'Антитела к бета-2-гликопротеину I IgG', 'name_kk': 'Бета-2-гликопротеин I-ге антиденелер IgG', 'abbr': 'Anti-β2GP1 IgG'},
    {'name': 'Антитела к бета-2-гликопротеину I IgM', 'unit': 'Ед/мл', 'name_en': 'Anti-Beta-2-Glycoprotein I IgM', 'name_ru': 'Антитела к бета-2-гликопротеину I IgM', 'name_kk': 'Бета-2-гликопротеин I-ге антиденелер IgM', 'abbr': 'Anti-β2GP1 IgM'},

    # 7. Tumor Markers / Онкомаркеры / Онкомаркерлер
    {'name': 'Простат-специфический антиген общий', 'unit': 'нг/мл', 'name_en': 'Prostate Specific Antigen, Total', 'name_ru': 'Простат-специфический антиген общий', 'name_kk': 'Простата-спецификалық антиген жалпы', 'abbr': 'PSA,ПСА общий,ПСА'},
    {'name': 'Простат-специфический антиген свободный', 'unit': 'нг/мл', 'name_en': 'Prostate Specific Antigen, Free', 'name_ru': 'Простат-специфический антиген свободный', 'name_kk': 'Простата-спецификалық антиген бос', 'abbr': 'fPSA,ПСА своб,Свободный ПСА'},
    {'name': 'Раково-эмбриональный антиген', 'unit': 'нг/мл', 'name_en': 'Carcinoembryonic Antigen', 'name_ru': 'Раково-эмбриональный антиген', 'name_kk': 'Рактік-эмбриондық антиген', 'abbr': 'CEA,РЭА'},
    {'name': 'Углеводный антиген 19-9', 'unit': 'Ед/мл', 'name_en': 'Carbohydrate Antigen 19-9', 'name_ru': 'Углеводный антиген 19-9', 'name_kk': 'Көмірсутекті антиген 19-9', 'abbr': 'CA 19-9'},
    {'name': 'Раковый антиген 125', 'unit': 'Ед/мл', 'name_en': 'Cancer Antigen 125', 'name_ru': 'Раковый антиген 125', 'name_kk': 'Рактік антиген 125', 'abbr': 'CA 125'},
    {'name': 'Раковый антиген 15-3', 'unit': 'Ед/мл', 'name_en': 'Cancer Antigen 15-3', 'name_ru': 'Раковый антиген 15-3', 'name_kk': 'Рактік антиген 15-3', 'abbr': 'CA 15-3'},
    {'name': 'Альфа-фетопротеин', 'unit': 'МЕ/мл', 'name_en': 'Alpha-fetoprotein', 'name_ru': 'Альфа-фетопротеин', 'name_kk': 'Альфа-фетопротеин', 'abbr': 'AFP,АФП'},
    {'name': 'Хорионический гонадотропин человека', 'unit': 'мМЕ/мл', 'name_en': 'Human Chorionic Gonadotropin', 'name_ru': 'Хорионический гонадотропин человека', 'name_kk': 'Адам хориондық гонадотропині', 'abbr': 'hCG,ХГЧ,Бета-ХГЧ,β-ХГЧ'},
    {'name': 'Нейронспецифическая енолаза', 'unit': 'нг/мл', 'name_en': 'Neuron-Specific Enolase', 'name_ru': 'Нейронспецифическая енолаза', 'name_kk': 'Нейронспецификалық енолаза', 'abbr': 'NSE,НСЕ'},
    {'name': 'Раковый антиген 72-4', 'unit': 'Ед/мл', 'name_en': 'Cancer Antigen 72-4', 'name_ru': 'Раковый антиген 72-4', 'name_kk': 'Рактік антиген 72-4', 'abbr': 'CA 72-4'},
    {'name': 'Раковый антиген 242', 'unit': 'Ед/мл', 'name_en': 'Cancer Antigen 242', 'name_ru': 'Раковый антиген 242', 'name_kk': 'Рактік антиген 242', 'abbr': 'CA 242'},
    {'name': 'Белок S-100', 'unit': 'мкг/л', 'name_en': 'Protein S-100', 'name_ru': 'Белок S-100', 'name_kk': 'S-100 белогы', 'abbr': 'S-100'},
    {'name': 'Хромогранин A', 'unit': 'нг/мл', 'name_en': 'Chromogranin A', 'name_ru': 'Хромогранин A', 'name_kk': 'Хромогранин A', 'abbr': 'CgA'},
    {'name': 'Антиген плоскоклеточной карциномы', 'unit': 'нг/мл', 'name_en': 'Squamous Cell Carcinoma Antigen', 'name_ru': 'Антиген плоскоклеточной карциномы', 'name_kk': 'Жалпақ жасушалы карцинома антигені', 'abbr': 'SCC'},
    {'name': 'Cyfra 21-1', 'unit': 'нг/мл', 'name_en': 'Cyfra 21-1', 'name_ru': 'Cyfra 21-1', 'name_kk': 'Cyfra 21-1', 'abbr': 'Cyfra 21-1'},
    {'name': 'HE4', 'unit': 'пмоль/л', 'name_en': 'Human Epididymis Protein 4', 'name_ru': 'HE4', 'name_kk': 'HE4', 'abbr': 'HE4'},

    # 8. Toxicology / Drug Monitoring / Токсикология / Лекарственный мониторинг / Токсикология / Дәрілік мониторинг
    {'name': 'Алкоголь в крови', 'unit': 'г/л', 'name_en': 'Blood Alcohol Concentration', 'name_ru': 'Алкоголь в крови', 'name_kk': 'Қандағы алкоголь', 'abbr': 'BAC,Этанол'},
    {'name': 'Парацетамол', 'unit': 'мкг/мл', 'name_en': 'Paracetamol', 'name_ru': 'Парацетамол', 'name_kk': 'Парацетамол', 'abbr': 'Paracetamol,Acetaminophen'},
    {'name': 'Салицилаты', 'unit': 'мг/дл', 'name_en': 'Salicylate', 'name_ru': 'Салицилаты', 'name_kk': 'Салицилаттар', 'abbr': 'Salicylate'},
    {'name': 'Фенитоин', 'unit': 'мкг/мл', 'name_en': 'Phenytoin', 'name_ru': 'Фенитоин', 'name_kk': 'Фенитоин', 'abbr': 'Phenytoin,Дифенин'},
    {'name': 'Дигоксин', 'unit': 'нг/мл', 'name_en': 'Digoxin', 'name_ru': 'Дигоксин', 'name_kk': 'Дигоксин', 'abbr': 'Digoxin'},
    {'name': 'Литий', 'unit': 'ммоль/л', 'name_en': 'Lithium', 'name_ru': 'Литий', 'name_kk': 'Литий', 'abbr': 'Lithium,Li'},
    {'name': 'Вальпроевая кислота', 'unit': 'мкг/мл', 'name_en': 'Valproic Acid', 'name_ru': 'Вальпроевая кислота', 'name_kk': 'Вальпрой қышқылы', 'abbr': 'Valproate,Депакин,Вальпроат'},
    {'name': 'Карбамазепин', 'unit': 'мкг/мл', 'name_en': 'Carbamazepine', 'name_ru': 'Карбамазепин', 'name_kk': 'Карбамазепин', 'abbr': 'Carbamazepine,Финлепсин,Тегретол'},
    {'name': 'Ванкомицин', 'unit': 'мкг/мл', 'name_en': 'Vancomycin', 'name_ru': 'Ванкомицин', 'name_kk': 'Ванкомицин', 'abbr': 'Vanco'},
    {'name': 'Гентамицин', 'unit': 'мкг/мл', 'name_en': 'Gentamicin', 'name_ru': 'Гентамицин', 'name_kk': 'Гентамицин', 'abbr': 'Genta'},
    {'name': 'Фенобарбитал', 'unit': 'мкг/мл', 'name_en': 'Phenobarbital', 'name_ru': 'Фенобарбитал', 'name_kk': 'Фенобарбитал', 'abbr': 'Phenobarbital'},
    {'name': 'Теофиллин', 'unit': 'мкг/мл', 'name_en': 'Theophylline', 'name_ru': 'Теофиллин', 'name_kk': 'Теофиллин', 'abbr': 'Theophylline'},
    {'name': 'Ламотриджин', 'unit': 'мкг/мл', 'name_en': 'Lamotrigine', 'name_ru': 'Ламотриджин', 'name_kk': 'Ламотриджин', 'abbr': 'Lamotrigine,Ламиктал'},
    {'name': 'Леветирацетам', 'unit': 'мкг/мл', 'name_en': 'Levetiracetam', 'name_ru': 'Леветирацетам', 'name_kk': 'Леветирацетам', 'abbr': 'Levetiracetam,Кеппра'},

    # 9. Miscellaneous / Other Panels / Разное / Прочие панели / Әртүрлі / Басқа панельдер
    {'name': 'Витамин B12', 'unit': 'пг/мл', 'name_en': 'Vitamin B12', 'name_ru': 'Витамин B12', 'name_kk': 'В12 дәрумені', 'abbr': 'Vit B12,Цианокобаламин,Кобаламин'},
    {'name': 'Фолиевая кислота', 'unit': 'нг/мл', 'name_en': 'Folate', 'name_ru': 'Фолиевая кислота', 'name_kk': 'Фолий қышқылы', 'abbr': 'Folate,Фолат,Витамин B9'},
    {'name': 'Ферритин', 'unit': 'нг/мл', 'name_en': 'Ferritin', 'name_ru': 'Ферритин', 'name_kk': 'Ферритин', 'abbr': 'Ferritin'},
    {'name': 'Железо сывороточное', 'unit': 'мкмоль/л', 'name_en': 'Iron, Serum', 'name_ru': 'Железо сывороточное', 'name_kk': 'Сарысулық темір', 'abbr': 'Fe,Iron,Железо'},
    {'name': 'Общая железосвязывающая способность сыворотки', 'unit': 'мкмоль/л', 'name_en': 'Total Iron Binding Capacity', 'name_ru': 'Общая железосвязывающая способность сыворотки', 'name_kk': 'Сарысудың жалпы темір байланыстыру қабілеті', 'abbr': 'TIBC,ОЖСС'},
    {'name': 'Трансферрин', 'unit': 'г/л', 'name_en': 'Transferrin', 'name_ru': 'Трансферрин', 'name_kk': 'Трансферрин', 'abbr': 'Transferrin'},
    {'name': 'Насыщение трансферрина железом', 'unit': '%', 'name_en': 'Transferrin Saturation', 'name_ru': 'Насыщение трансферрина железом', 'name_kk': 'Трансферриннің темірмен қанығуы', 'abbr': 'TSAT,% насыщения трансферрина,Коэффициент насыщения трансферрина'},
    {'name': 'Витамин D (25-OH)', 'unit': 'нг/мл', 'name_en': 'Vitamin D (25-OH)', 'name_ru': 'Витамин D (25-OH)', 'name_kk': 'D дәрумені (25-OH)', 'abbr': 'Vit D,25-OH D,25-гидроксивитамин D,Витамин D общий'},
    {'name': 'Амилаза', 'unit': 'Ед/л', 'name_en': 'Amylase', 'name_ru': 'Амилаза', 'name_kk': 'Амилаза', 'abbr': 'Amylase,AMY,Альфа-амилаза,Амилаза общая'},
    {'name': 'Амилаза панкреатическая', 'unit': 'Ед/л', 'name_en': 'Pancreatic Amylase', 'name_ru': 'Амилаза панкреатическая', 'name_kk': 'Панкреатикалық амилаза', 'abbr': 'P-AMY,Панкреатическая амилаза'},
    {'name': 'Липаза', 'unit': 'Ед/л', 'name_en': 'Lipase', 'name_ru': 'Липаза', 'name_kk': 'Липаза', 'abbr': 'Lipase,LIP'},
    {'name': 'Гомоцистеин', 'unit': 'мкмоль/л', 'name_en': 'Homocysteine', 'name_ru': 'Гомоцистеин', 'name_kk': 'Гомоцистеин', 'abbr': 'Homocysteine'},
    {'name': 'Церулоплазмин', 'unit': 'мг/дл', 'name_en': 'Ceruloplasmin', 'name_ru': 'Церулоплазмин', 'name_kk': 'Церулоплазмин', 'abbr': 'Ceruloplasmin'},
    {'name': 'Медь', 'unit': 'мкг/дл', 'name_en': 'Copper', 'name_ru': 'Медь', 'name_kk': 'Мыс', 'abbr': 'Copper,Cu'},
    {'name': 'Цинк', 'unit': 'мкг/дл', 'name_en': 'Zinc', 'name_ru': 'Цинк', 'name_kk': 'Мырыш', 'abbr': 'Zinc,Zn'},
    {'name': 'Гастрин', 'unit': 'пг/мл', 'name_en': 'Gastrin', 'name_ru': 'Гастрин', 'name_kk': 'Гастрин', 'abbr': 'Gastrin'},
    {'name': 'Пепсиноген I', 'unit': 'нг/мл', 'name_en': 'Pepsinogen I', 'name_ru': 'Пепсиноген I', 'name_kk': 'Пепсиноген I', 'abbr': 'PGI,Пепсиноген-I'},
    {'name': 'Пепсиноген II', 'unit': 'нг/мл', 'name_en': 'Pepsinogen II', 'name_ru': 'Пепсиноген II', 'name_kk': 'Пепсиноген II', 'abbr': 'PGII,Пепсиноген-II'},
    {'name': 'Остеокальцин', 'unit': 'нг/мл', 'name_en': 'Osteocalcin', 'name_ru': 'Остеокальцин', 'name_kk': 'Остеокальцин', 'abbr': 'Osteocalcin'},
    {'name': 'Beta-CrossLaps', 'unit': 'нг/мл', 'name_en': 'Beta-CrossLaps', 'name_ru': 'Beta-CrossLaps', 'name_kk': 'Beta-CrossLaps', 'abbr': 'Beta-CrossLaps,β-CrossLaps,CTX'},
    {'name': 'P1NP', 'unit': 'нг/мл', 'name_en': 'Procollagen Type 1 N-Terminal Propeptide', 'name_ru': 'P1NP', 'name_kk': 'P1NP', 'abbr': 'P1NP,Общий P1NP'},
    # Добавьте другие аналиты по мере необходимости
]

def populate_analyte_data(apps, schema_editor):
    """
    Заполняет модель Analyte данными из списка ANALYTES_DATA.
    """
    Analyte = apps.get_model('data', 'Analyte')
    db_alias = schema_editor.connection.alias
    existing_names = set(Analyte.objects.using(db_alias).values_list('name', flat=True))
    analytes_to_create = []
    for item in ANALYTES_DATA:
        if item['name'] not in existing_names:
            analytes_to_create.append(
                Analyte(
                    name=item['name'],
                    unit=item['unit'],
                    name_en=item.get('name_en', ''),
                    name_ru=item.get('name_ru', ''),
                    name_kk=item.get('name_kk', ''),
                    abbreviations=item.get('abbr', '')
                )
            )
            existing_names.add(item['name'])
        # else:
            # print(f"Analyte '{item['name']}' already exists, skipping.")

    if analytes_to_create:
        print(f"\nCreating {len(analytes_to_create)} new analytes...")
        Analyte.objects.using(db_alias).bulk_create(analytes_to_create, ignore_conflicts=True)
        print("Analyte data population complete.")
    else:
        print("\nNo new analytes to create.")

def reverse_code(apps, schema_editor):
    """
    Код для отката миграции (удаление добавленных типов).
    """
    pass # Оставляем пустым, чтобы не удалять данные при откате

class Migration(migrations.Migration):

    dependencies = [
        # Замените '0002_...' на имя вашей *последней* миграции схемы для 'data'
        # перед созданием 0003_populate_analytes
        ('data', '0004_populate_test_types'), # <-- ЗАМЕНИТЕ НА ВАШЕ ИМЯ ФАЙЛА!
    ]

    operations = [
        migrations.RunPython(populate_analyte_data, reverse_code=reverse_code),
    ]

