# Generated by Django 5.2 on 2025-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_populate_analytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyte',
            name='typical_test_types',
            field=models.ManyToManyField(blank=True, related_name='typical_analytes', to='data.testtype', verbose_name='Typical Test Types'),
        ),
        migrations.AddField(
            model_name='testtype',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords found in PDF titles or headers (e.g., ОАК,CBC,Биохимия)', max_length=255, null=True, verbose_name='Keywords for Identification'),
        ),
        migrations.AlterField(
            model_name='analyte',
            name='abbreviations',
            field=models.CharField(blank=True, help_text='Common abbreviations, e.g., Hb, Hgb, HCT, Plt, АЛТ, АСТ, ТТГ', max_length=500, verbose_name='Abbreviations (comma-separated)'),
        ),
    ]
