# Generated by Django 5.2 on 2025-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_link_analytes_to_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='status_text',
            field=models.CharField(blank=True, help_text="Status text found in the report (e.g., 'В норме', 'Ниже нормы').", max_length=100, null=True, verbose_name='Status Text'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='is_abnormal',
            field=models.BooleanField(blank=True, db_index=True, help_text='Indicates if the value falls outside the reference range or marked as abnormal.', null=True, verbose_name='Is Abnormal?'),
        ),
    ]
