# Generated by Django 5.2 on 2025-05-07 23:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_testresult_status_text_alter_testresult_is_abnormal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('symptoms_prompt', models.TextField(blank=True, help_text='Symptoms provided by the user.', verbose_name='User Symptoms Prompt')),
                ('analyte_data_snapshot', models.JSONField(blank=True, help_text='JSON snapshot of analyte data used for this summary.', null=True, verbose_name='Analyte Data Snapshot')),
                ('ai_raw_response', models.TextField(blank=True, help_text='Full response from the AI model, if available.', null=True, verbose_name='AI Raw Response')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI Overall Summary')),
                ('ai_key_findings', models.JSONField(blank=True, default=list, help_text='List of key findings strings.', verbose_name='AI Key Findings')),
                ('ai_detailed_breakdown', models.JSONField(blank=True, default=list, help_text='List of objects detailing metric changes and comments.', verbose_name='AI Detailed Breakdown')),
                ('ai_suggested_diagnosis', models.CharField(blank=True, max_length=255, verbose_name='AI Suggested Diagnosis')),
                ('is_confirmed', models.BooleanField(db_index=True, default=False, verbose_name='Is Confirmed?')),
                ('confirmed_diagnosis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Confirmed Diagnosis')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_summaries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Health Summary',
                'verbose_name_plural': 'Health Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
